import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { SEOSection } from '@jjlmoya/utils-shared';
import type { ToolLocaleContent } from '../../../types';
import type { WallpaperRollCalculatorUI } from '../ui';
import { bibliography } from '../bibliography';

type Locale =
  | 'de'
  | 'en'
  | 'es'
  | 'fr'
  | 'id'
  | 'it'
  | 'ja'
  | 'ko'
  | 'nl'
  | 'pl'
  | 'pt'
  | 'ru'
  | 'sv'
  | 'tr'
  | 'zh';

interface SeoCopy {
  introTitle: string;
  introParagraph: string;
  plainTitle: string;
  plainDescription: string;
  plainPoints: string[];
  patternedTitle: string;
  patternedDescription: string;
  patternedPoints: string[];
  meaningTitle: string;
  meaningParagraph: string;
  warningTitle: string;
  warningBadge: string;
  warningHtml: string;
  summaryTitle: string;
  summaryItems: string[];
}

interface Copy {
  slug: string;
  title: string;
  description: string;
  faq: ToolLocaleContent['faq'];
  howTo: ToolLocaleContent['howTo'];
  ui: WallpaperRollCalculatorUI;
  seo: SeoCopy;
  bibliographyNames: [string, string, string];
}

const baseBibliography = (names: [string, string, string]) =>
  bibliography.map((entry, index) => ({ ...entry, name: names[index] ?? entry.name }));

function createSchemas(copy: Copy, locale: Locale) {
  const faqSchema: WithContext<FAQPage> = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: copy.faq.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: { '@type': 'Answer', text: item.answer },
    })),
  };
  const howToSchema: WithContext<HowTo> = {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: copy.title,
    description: copy.description,
    step: copy.howTo.map((step) => ({
      '@type': 'HowToStep',
      name: step.name,
      text: step.text,
    })),
  };
  const appSchema: WithContext<SoftwareApplication> = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: copy.title,
    description: copy.description,
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'All',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
    inLanguage: locale,
  };
  return [faqSchema, howToSchema, appSchema];
}

function buildSeo(copy: Copy): SEOSection[] {
  const seo = copy.seo;
  return [
    { type: 'title', text: seo.introTitle, level: 2 },
    { type: 'paragraph', html: seo.introParagraph },
    {
      type: 'stats',
      items: [
        { value: copy.ui.labelRollsNeeded.toUpperCase(), label: copy.ui.labelDropsNeeded, icon: 'mdi:arrow-expand-horizontal' },
        { value: copy.ui.labelPatternRepeat.toUpperCase(), label: copy.ui.labelCutLength, icon: 'mdi:format-vertical-align-bottom' },
        { value: copy.ui.rollsNeededSuffix.toUpperCase(), label: copy.ui.labelRollsNeeded, icon: 'mdi:format-paint' },
      ],
      columns: 3,
    },
    {
      type: 'comparative',
      items: [
        { title: seo.plainTitle, description: seo.plainDescription, icon: 'mdi:wallpaper', points: seo.plainPoints },
        { title: seo.patternedTitle, description: seo.patternedDescription, icon: 'mdi:shape-outline', points: seo.patternedPoints },
      ],
      columns: 2,
    },
    { type: 'title', text: seo.meaningTitle, level: 3 },
    { type: 'paragraph', html: seo.meaningParagraph },
    {
      type: 'diagnostic',
      variant: 'warning',
      title: seo.warningTitle,
      icon: 'mdi:alert-outline',
      badge: seo.warningBadge,
      html: seo.warningHtml,
    },
    { type: 'summary', title: seo.summaryTitle, items: seo.summaryItems },
  ];
}

export function createWallpaperContent(locale: Locale): ToolLocaleContent<WallpaperRollCalculatorUI> {
  const copy = copies[locale];
  return {
    slug: copy.slug,
    title: copy.title,
    description: copy.description,
    ui: copy.ui,
    seo: buildSeo(copy),
    faq: copy.faq,
    bibliography: baseBibliography(copy.bibliographyNames),
    howTo: copy.howTo,
    schemas: createSchemas(copy, locale),
  };
}

const copies: Record<Locale, Copy> = {
  en: {
    slug: 'wallpaper-roll-calculator',
    title: 'Wallpaper Roll Calculator',
    description: 'Calculate how many wallpaper rolls you need from your wall size, roll dimensions, pattern repeat and waste allowance.',
    faq: [
      { question: 'How many wallpaper rolls do I need?', answer: 'Enter the wall width and height, roll width and roll length. The calculator turns the width into vertical drops, rounds each drop to the next pattern repeat and counts complete rolls.' },
      { question: 'What does pattern repeat mean?', answer: 'Pattern repeat is the vertical distance before the design starts again. A 53 cm repeat means each drop must be cut to a multiple of 53 cm so neighbouring strips line up.' },
      { question: 'Why can patterned wallpaper need more rolls?', answer: 'A repeating design can make every drop longer than the wall height. That extra length aligns the pattern and becomes offcut, reducing the drops obtained from each roll.' },
      { question: 'What waste allowance should I use?', answer: 'Use the allowance recommended by the manufacturer when available. For a first estimate, 10% is a practical starting point for cutting mistakes, damage and small offcuts.' },
      { question: 'Does this calculator include doors and windows?', answer: 'No. It uses the full wall width so the estimate remains conservative. Calculate the full wall first, then compare it with the manufacturer or installer recommendation.' },
    ],
    howTo: [
      { name: 'Measure the wall', text: 'Enter the total width to cover and the finished wall height in centimetres.' },
      { name: 'Read the roll label', text: 'Enter the roll width and total roll length shown on the product label.' },
      { name: 'Add the pattern repeat', text: 'Enter the vertical pattern repeat. Use zero for plain wallpaper with no matching repeat.' },
      { name: 'Check the buying decision', text: 'Use the roll count, drop count and leftover length to compare the estimate with the product instructions before buying.' },
    ],
    bibliographyNames: ['Erfurt: Rauhfaser tapezieren in 5 Schritten', 'Graham & Brown: How to Hang Wallpaper', 'Wallpaperdirect: Wallpaper Hanging Guide'],
    seo: {
      introTitle: 'Turn wall measurements into a buying decision', introParagraph: 'Wallpaper is sold in complete rolls, but walls are covered with vertical drops. The useful calculation is how many drops fit into one roll after each drop is rounded to the next pattern repeat.',
      plainTitle: 'Plain wallpaper', plainDescription: 'With no matching repeat, each drop is cut to the wall height and the roll length is divided into as many full drops as possible.', plainPoints: ['Set pattern repeat to 0 cm', 'Cut length equals wall height', 'Offcuts remain usable if the pattern allows it'],
      patternedTitle: 'Patterned wallpaper', patternedDescription: 'A repeating design needs each drop to finish on a matching point. The calculator rounds the drop up to a complete repeat before counting roll capacity.', patternedPoints: ['Read the repeat from the label', 'Align every drop to the same pattern', 'Extra length becomes visible leftover'],
      meaningTitle: 'What the result means', meaningParagraph: '<strong>Rolls needed</strong> is the number of complete rolls to buy. <strong>Drops needed</strong> is the number of vertical strips across the wall. <strong>Cut length</strong> includes pattern alignment. <strong>Leftover</strong> is the gross length remaining after the calculated drops are cut.',
      warningTitle: 'Use the product label as the final authority', warningBadge: 'Important limit', warningHtml: '<p>Manufacturers can specify matching methods, repeat conventions, batch limits or extra allowance. This is a transparent planning estimate, not a replacement for the label or an installer.</p>',
      summaryTitle: 'Before you buy', summaryItems: ['Measure the finished wall height.', 'Use the width and length printed on the exact roll label.', 'Check whether the repeat is straight match, drop match or random match.', 'Keep the same batch number when the manufacturer recommends it.', 'Buy enough for the full job because later batches may vary slightly in colour.'],
    },
    ui: {
      configTitle: 'Plan the wall', configSubtitle: 'Turn measurements into complete rolls', unitSystemLabel: 'Units', unitMetric: 'Metric', unitImperial: 'Imperial', roomTitle: 'Wall to cover', labelRoomWidth: 'Total wall width', labelWallHeight: 'Finished wall height', rollTitle: 'Roll label', labelRollWidth: 'Roll width', labelRollLength: 'Roll length', patternTitle: 'Pattern and reserve', labelPatternRepeat: 'Pattern repeat', patternHint: 'Use the vertical repeat printed on the label. Set 0 for plain or random-match wallpaper.', labelWasteAllowance: 'Waste allowance', wasteHint: 'This reserve reduces the roll length used for planning. Follow the manufacturer recommendation when available.', unitCentimetres: 'cm', unitInches: 'in', unitFeet: 'ft', unitPercent: '%', resultTitle: 'Your buying estimate', labelRollsNeeded: 'Complete rolls', rollsNeededSuffix: 'to buy', labelDropsNeeded: 'Drops across wall', labelDropsPerRoll: 'Drops per roll', labelCutLength: 'Cut length per drop', labelLeftover: 'Length left after cuts', visualBadge: 'Drop planning desk', invalidMeasurements: 'Check the measurements and use positive values.', rollTooShort: 'This roll is too short for one drop with the current pattern and allowance.', resetLabel: 'Reset example',
    },
  },
  ja: {
    slug: 'kabe-gami-roll-keisan', title: '壁紙ロール計算機', description: '壁の寸法、ロールのサイズ、柄のリピート、廃棄分から必要な壁紙ロール数を計算します。',
    faq: [{ question: '壁紙は何本必要ですか？', answer: '壁の幅と高さ、ロールの幅と長さを入力してください。柄のリピートを考慮して必要な縦の枚数とロール数を計算します。' }, { question: '柄のリピートとは何ですか？', answer: '柄がもう一度現れるまでの縦方向の距離です。隣り合う壁紙の柄を合わせるため、切断長さはリピートの倍数になります。' }, { question: '柄付き壁紙で本数が増える理由は？', answer: '柄合わせのために各枚の長さが壁の高さより長くなり、1本から取れる枚数が減ることがあります。' }, { question: '廃棄分は何パーセントにしますか？', answer: 'メーカーの指定があればそれに従ってください。最初の目安としては、切り間違いや小さな端材を考慮して10%が使えます。' }, { question: 'ドアや窓は計算に含まれますか？', answer: '含まれません。安全側の見積もりとして壁全体の幅を使い、購入前にメーカーや施工業者の案内も確認してください。' }],
    howTo: [{ name: '壁を測る', text: '施工する壁の全幅と仕上がり高さをセンチメートルで入力します。' }, { name: 'ロール表示を確認する', text: '商品ラベルにあるロール幅と全長を入力します。' }, { name: '柄のリピートを入力する', text: '縦方向のリピートを入力します。無地や柄合わせ不要の場合は0にします。' }, { name: '購入数を確認する', text: 'ロール数、必要な枚数、切断後の残りを商品説明の数値と比較します。' }],
    bibliographyNames: ['Erfurt：壁紙を貼る5つの手順', 'Graham & Brown：壁紙の貼り方', 'Wallpaperdirect：壁紙施工ガイド'],
    seo: { introTitle: '壁の寸法を購入数に変える', introParagraph: '壁紙はロール単位で販売されますが、壁は縦の枚で覆います。柄のリピートに合わせて切ったあと、1本から何枚取れるかが重要です。', plainTitle: '無地の壁紙', plainDescription: '柄合わせがない場合、各枚は壁の高さで切り、ロールの長さから取れる完全な枚数を数えます。', plainPoints: ['リピートを0cmにする', '切断長さは壁の高さと同じ', '種類によって端材も利用できる'], patternedTitle: '柄付き壁紙', patternedDescription: '繰り返し柄では、各枚を柄が合う位置で終わらせます。計算機は容量を数える前に切断長さを切り上げます。', patternedPoints: ['ラベルからリピートを読む', 'すべての枚の柄を揃える', '余分な長さを残りとして確認する'], meaningTitle: '結果の見方', meaningParagraph: '<strong>必要ロール数</strong>は購入する完全なロール数です。<strong>必要枚数</strong>は壁を覆う縦の枚数、<strong>1枚の切断長さ</strong>は柄合わせ込み、<strong>残り</strong>は切断後の総残量です。', warningTitle: '最終判断は商品ラベルで行う', warningBadge: '重要な注意', warningHtml: '<p>メーカーは柄合わせ、ロット、追加の余裕について独自の指定をすることがあります。この見積もりはラベルや施工業者の助言の代わりにはなりません。</p>', summaryTitle: '購入前に確認', summaryItems: ['仕上がりの壁高を測る。', '購入するロールのラベル寸法を使う。', '柄が直線、ずらし、またはフリーか確認する。', 'メーカーが指定する場合は同じロットを選ぶ。', '工事全体に必要な本数を一度に確保する。'] },
    ui: { configTitle: '壁を計画する', configSubtitle: '寸法を必要なロール数に変換', unitSystemLabel: '単位', unitMetric: 'メートル法', unitImperial: 'ヤード・ポンド法', roomTitle: '施工する壁', labelRoomWidth: '壁の全幅', labelWallHeight: '仕上がり高さ', rollTitle: 'ロールのラベル', labelRollWidth: 'ロール幅', labelRollLength: 'ロール長さ', patternTitle: '柄と予備', labelPatternRepeat: '柄のリピート', patternHint: 'ラベルの縦リピートを使います。無地やランダム柄は0にします。', labelWasteAllowance: '廃棄分', wasteHint: 'この予備分を差し引いて計画します。メーカーの指定があれば従ってください。', unitCentimetres: 'cm', unitInches: 'インチ', unitFeet: 'フィート', unitPercent: '%', resultTitle: '購入目安', labelRollsNeeded: '完全なロール', rollsNeededSuffix: '購入', labelDropsNeeded: '壁の枚数', labelDropsPerRoll: '1本あたりの枚数', labelCutLength: '1枚の切断長さ', labelLeftover: '切断後の残り', visualBadge: '枚数計画', invalidMeasurements: '寸法を確認し、正の数を入力してください。', rollTooShort: '現在の柄と予備では、このロールから1枚を取れません。', resetLabel: '例をリセット' },
  },
  ko: {
    slug: 'byeokji-roll-gyesangi', title: '벽지 롤 계산기', description: '벽 크기, 롤 규격, 패턴 반복과 손실 여유를 기준으로 필요한 벽지 롤 수를 계산합니다.',
    faq: [{ question: '벽지 롤이 몇 개 필요한가요?', answer: '벽의 너비와 높이, 롤의 너비와 길이를 입력하세요. 패턴 반복을 반영해 필요한 세로 시트와 전체 롤 수를 계산합니다.' }, { question: '패턴 반복은 무엇인가요?', answer: '디자인이 다시 시작되는 세로 거리입니다. 이웃한 시트의 무늬를 맞추려면 절단 길이가 반복 길이의 배수가 되어야 합니다.' }, { question: '무늬 벽지는 왜 더 많이 필요한가요?', answer: '무늬를 맞추면 각 시트가 벽 높이보다 길어질 수 있습니다. 이 추가 길이 때문에 롤 하나에서 얻는 시트 수가 줄어듭니다.' }, { question: '손실 여유는 얼마로 설정하나요?', answer: '제조사 권장값을 우선 사용하세요. 처음 계산할 때는 절단 실수와 작은 자투리를 위해 10%를 기준으로 삼을 수 있습니다.' }, { question: '문과 창문도 계산되나요?', answer: '계산되지 않습니다. 보수적인 결과를 위해 벽 전체 너비를 사용하므로 구매 전에 제조사나 시공자의 안내를 확인하세요.' }],
    howTo: [{ name: '벽 측정', text: '시공할 전체 너비와 마감 높이를 센티미터로 입력합니다.' }, { name: '롤 라벨 확인', text: '제품 라벨에 표시된 롤 너비와 전체 길이를 입력합니다.' }, { name: '패턴 반복 입력', text: '세로 반복 길이를 입력합니다. 무지 벽지나 맞춤이 없으면 0을 사용합니다.' }, { name: '구매 수량 확인', text: '롤 수와 시트 수, 절단 후 남는 길이를 제품 안내와 비교합니다.' }],
    bibliographyNames: ['Erfurt: 벽지 시공 5단계', 'Graham & Brown: 벽지 붙이는 방법', 'Wallpaperdirect: 벽지 시공 가이드'],
    seo: { introTitle: '벽 치수를 구매 수량으로 바꾸기', introParagraph: '벽지는 완성된 롤로 판매되지만 벽은 세로 시트로 덮습니다. 패턴 반복에 맞춰 자른 뒤 롤 하나에서 몇 장이 나오는지가 핵심입니다.', plainTitle: '무지 벽지', plainDescription: '맞춤 무늬가 없다면 시트는 벽 높이에 맞춰 자르고 롤 길이에서 완성된 시트 수를 계산합니다.', plainPoints: ['반복 길이를 0cm로 설정', '절단 길이는 벽 높이와 동일', '종류에 따라 자투리도 활용 가능'], patternedTitle: '무늬 벽지', patternedDescription: '반복 무늬는 각 시트가 맞는 지점에서 끝나야 합니다. 계산기는 롤 용량을 세기 전에 절단 길이를 올림합니다.', patternedPoints: ['라벨에서 반복 길이 확인', '모든 시트의 무늬 정렬', '추가 길이를 남은 길이로 확인'], meaningTitle: '결과 이해하기', meaningParagraph: '<strong>필요 롤 수</strong>는 구매할 완성 롤 수입니다. <strong>필요 시트 수</strong>는 벽을 덮는 세로 조각 수이며, <strong>절단 길이</strong>에는 무늬 맞춤이 포함됩니다. <strong>남은 길이</strong>는 절단 후 남는 전체 길이입니다.', warningTitle: '최종 기준은 제품 라벨', warningBadge: '중요한 한계', warningHtml: '<p>제조사는 무늬 맞춤, 생산 배치, 추가 여유에 관한 별도 조건을 제시할 수 있습니다. 이 추정치는 라벨이나 전문가의 조언을 대신하지 않습니다.</p>', summaryTitle: '구매 전 확인', summaryItems: ['마감된 벽 높이를 잰다.', '선택한 롤 라벨의 규격을 사용한다.', '무늬가 직선, 엇갈림, 또는 자유 맞춤인지 확인한다.', '제조사가 권하면 같은 배치를 구매한다.', '전체 작업에 필요한 롤을 충분히 준비한다.'] },
    ui: { configTitle: '벽 계획하기', configSubtitle: '치수를 완성 롤 수로 변환', unitSystemLabel: '단위', unitMetric: '미터법', unitImperial: '야드파운드법', roomTitle: '시공할 벽', labelRoomWidth: '벽 전체 너비', labelWallHeight: '마감 벽 높이', rollTitle: '롤 라벨', labelRollWidth: '롤 너비', labelRollLength: '롤 길이', patternTitle: '패턴과 여유', labelPatternRepeat: '패턴 반복', patternHint: '라벨에 적힌 세로 반복을 사용하세요. 무지나 자유 맞춤은 0으로 설정합니다.', labelWasteAllowance: '손실 여유', wasteHint: '이 여유만큼 계획에 사용할 롤 길이를 줄입니다. 제조사 권장값을 따르세요.', unitCentimetres: 'cm', unitInches: '인치', unitFeet: '피트', unitPercent: '%', resultTitle: '구매 추정', labelRollsNeeded: '완성 롤', rollsNeededSuffix: '구매', labelDropsNeeded: '벽 시트 수', labelDropsPerRoll: '롤당 시트 수', labelCutLength: '시트당 절단 길이', labelLeftover: '절단 후 남은 길이', visualBadge: '시트 계획표', invalidMeasurements: '치수를 확인하고 양수를 입력하세요.', rollTooShort: '현재 패턴과 여유를 적용하면 이 롤은 한 시트도 만들기 어렵습니다.', resetLabel: '예시 초기화' },
  },
  nl: {
    slug: 'behangrollen-calculator', title: 'Calculator voor behangrollen', description: 'Bereken hoeveel behangrollen je nodig hebt op basis van de muur, rolmaten, patroonherhaling en snijverlies.',
    faq: [{ question: 'Hoeveel behangrollen heb ik nodig?', answer: 'Vul de breedte en hoogte van de muur en de breedte en lengte van de rol in. De calculator telt verticale banen, houdt rekening met het patroon en bepaalt het aantal hele rollen.' }, { question: 'Wat betekent patroonherhaling?', answer: 'Dit is de verticale afstand waarna het motief opnieuw begint. Elke baan wordt op een veelvoud daarvan gesneden zodat de aangrenzende banen aansluiten.' }, { question: 'Waarom heb ik bij behang met motief meer rollen nodig?', answer: 'Door het aansluiten van het motief kan iedere baan langer worden dan de muur. Daardoor passen er minder banen uit één rol.' }, { question: 'Welke marge voor snijverlies gebruik ik?', answer: 'Volg de aanbeveling van de fabrikant. Voor een eerste schatting is 10% praktisch voor snijfouten, beschadiging en kleine resten.' }, { question: 'Houdt deze calculator rekening met deuren en ramen?', answer: 'Nee. De volledige muurbreedte geeft een voorzichtige schatting. Vergelijk het resultaat voor aankoop met de fabrikant of behanger.' }],
    howTo: [{ name: 'Meet de muur', text: 'Vul de totale te bedekken breedte en de afgewerkte hoogte in centimeters in.' }, { name: 'Lees het rollabel', text: 'Neem de rolbreedte en totale rollengte over van het productlabel.' }, { name: 'Voeg de patroonherhaling toe', text: 'Vul de verticale herhaling in. Gebruik nul voor effen behang zonder patroonmatch.' }, { name: 'Controleer de aankoop', text: 'Vergelijk rollen, banen en restlengte met de productinstructies voordat je koopt.' }],
    bibliographyNames: ['Erfurt: Glasvezelbehang aanbrengen in 5 stappen', 'Graham & Brown: Behang aanbrengen', 'Wallpaperdirect: Handleiding behangen'],
    seo: { introTitle: 'Van muurmaat naar aankoopbeslissing', introParagraph: 'Behang wordt per hele rol verkocht, terwijl je een muur met verticale banen bedekt. De nuttige berekening is hoeveel banen na de patroonherhaling in één rol passen.', plainTitle: 'Effen behang', plainDescription: 'Zonder patroonmatch wordt iedere baan op de muurhoogte gesneden en deel je de rollengte door het aantal volledige banen.', plainPoints: ['Zet de herhaling op 0 cm', 'De snijlengte is de muurhoogte', 'Reststukken kunnen bruikbaar blijven'], patternedTitle: 'Behang met patroon', patternedDescription: 'Bij een herhalend motief moet iedere baan op een passend punt eindigen. De calculator rondt de snede af voordat de rolcapaciteit wordt geteld.', patternedPoints: ['Lees de herhaling op het label', 'Laat alle banen aansluiten', 'Zie extra lengte als restmateriaal'], meaningTitle: 'De uitkomst begrijpen', meaningParagraph: '<strong>Benodigde rollen</strong> is het aantal hele rollen dat je koopt. <strong>Benodigde banen</strong> zijn de verticale stroken op de muur. De <strong>snijlengte</strong> bevat de patroonmatch en de <strong>rest</strong> is de bruto lengte na het snijden.', warningTitle: 'Het productlabel blijft leidend', warningBadge: 'Belangrijke beperking', warningHtml: '<p>Fabrikanten kunnen eigen matchmethodes, batchlimieten of extra marge voorschrijven. Deze planning vervangt het label of advies van een vakman niet.</p>', summaryTitle: 'Voor je koopt', summaryItems: ['Meet de afgewerkte muurhoogte.', 'Gebruik de maten van de gekozen rol.', 'Controleer rechte, verspringende of vrije match.', 'Koop dezelfde batch als de fabrikant dat adviseert.', 'Neem genoeg rollen voor het hele project.'] },
    ui: { configTitle: 'Plan de muur', configSubtitle: 'Zet maten om in hele rollen', unitSystemLabel: 'Eenheden', unitMetric: 'Metrisch', unitImperial: 'Imperiaal', roomTitle: 'Te bedekken muur', labelRoomWidth: 'Totale muurbreedte', labelWallHeight: 'Afgewerkte muurhoogte', rollTitle: 'Rollabel', labelRollWidth: 'Rolbreedte', labelRollLength: 'Rollengte', patternTitle: 'Patroon en reserve', labelPatternRepeat: 'Patroonherhaling', patternHint: 'Gebruik de verticale herhaling van het label. Zet 0 voor effen of vrije match.', labelWasteAllowance: 'Marge voor snijverlies', wasteHint: 'Deze reserve verlaagt de bruikbare rollengte. Volg de aanbeveling van de fabrikant.', unitCentimetres: 'cm', unitInches: 'inch', unitFeet: 'ft', unitPercent: '%', resultTitle: 'Je aankoopinschatting', labelRollsNeeded: 'Hele rollen', rollsNeededSuffix: 'te kopen', labelDropsNeeded: 'Banen op de muur', labelDropsPerRoll: 'Banen per rol', labelCutLength: 'Snijlengte per baan', labelLeftover: 'Rest na snijden', visualBadge: 'Banenplanning', invalidMeasurements: 'Controleer de maten en gebruik positieve waarden.', rollTooShort: 'Deze rol is te kort voor één baan met de huidige patroon- en reservemarge.', resetLabel: 'Voorbeeld resetten' },
  },
  pl: {
    slug: 'kalkulator-rol-tapety', title: 'Kalkulator rolek tapety', description: 'Oblicz liczbę potrzebnych rolek tapety na podstawie wymiarów ściany, rolki, raportu wzoru i zapasu na odpady.',
    faq: [{ question: 'Ile rolek tapety potrzebuję?', answer: 'Podaj szerokość i wysokość ściany oraz szerokość i długość rolki. Kalkulator policzy pionowe bryty, uwzględni raport wzoru i wyznaczy liczbę pełnych rolek.' }, { question: 'Co oznacza raport wzoru?', answer: 'To pionowa odległość, po której wzór zaczyna się ponownie. Każdy bryt trzeba przyciąć do wielokrotności raportu, aby sąsiednie pasy pasowały.' }, { question: 'Dlaczego tapeta we wzory może wymagać większej liczby rolek?', answer: 'Dopasowanie wzoru może wydłużyć każdy bryt ponad wysokość ściany. Dodatkowa długość zmniejsza liczbę brytów z jednej rolki.' }, { question: 'Jaki zapas odpadów przyjąć?', answer: 'Najpierw sprawdź zalecenie producenta. Do wstępnego szacunku 10% pokrywa błędy cięcia, uszkodzenia i małe ścinki.' }, { question: 'Czy kalkulator uwzględnia drzwi i okna?', answer: 'Nie. Pełna szerokość ściany daje ostrożny wynik. Przed zakupem porównaj go z zaleceniami producenta lub wykonawcy.' }],
    howTo: [{ name: 'Zmierz ścianę', text: 'Wpisz całkowitą szerokość do pokrycia i gotową wysokość ściany w centymetrach.' }, { name: 'Sprawdź etykietę rolki', text: 'Wpisz szerokość i całkowitą długość podane na etykiecie produktu.' }, { name: 'Dodaj raport wzoru', text: 'Wpisz pionowy raport. Dla tapety gładkiej lub bez dopasowania użyj zera.' }, { name: 'Sprawdź zakup', text: 'Porównaj liczbę rolek, brytów i pozostałej długości z instrukcją produktu.' }],
    bibliographyNames: ['Erfurt: Tapetowanie w 5 krokach', 'Graham & Brown: Jak tapetować', 'Wallpaperdirect: Poradnik tapetowania'],
    seo: { introTitle: 'Zamień wymiary ściany na decyzję zakupową', introParagraph: 'Tapeta jest sprzedawana w pełnych rolkach, a ścianę pokrywa się pionowymi brytami. Najważniejsze jest to, ile brytów mieści się w rolce po dopasowaniu raportu.', plainTitle: 'Tapeta bez raportu', plainDescription: 'Bez powtarzającego się wzoru każdy bryt przycina się do wysokości ściany, a długość rolki dzieli na pełne bryty.', plainPoints: ['Ustaw raport na 0 cm', 'Długość cięcia równa się wysokości ściany', 'Ścinki mogą pozostać użyteczne'], patternedTitle: 'Tapeta wzorzysta', patternedDescription: 'Powtarzalny wzór wymaga zakończenia każdego brytu w pasującym miejscu. Kalkulator zaokrągla cięcie przed obliczeniem pojemności rolki.', patternedPoints: ['Odczytaj raport z etykiety', 'Dopasuj każdy bryt', 'Potraktuj dodatkową długość jako odpad'], meaningTitle: 'Jak czytać wynik', meaningParagraph: '<strong>Potrzebne rolki</strong> to liczba pełnych rolek do kupienia. <strong>Potrzebne bryty</strong> to pionowe pasy na ścianie. <strong>Długość cięcia</strong> uwzględnia dopasowanie wzoru, a <strong>pozostałość</strong> to długość po cięciu.', warningTitle: 'Etykieta produktu ma ostatnie słowo', warningBadge: 'Ważne ograniczenie', warningHtml: '<p>Producent może podać własny sposób dopasowania, ograniczenia partii lub dodatkowy zapas. Ten wynik nie zastępuje etykiety ani porady fachowca.</p>', summaryTitle: 'Przed zakupem', summaryItems: ['Zmierz gotową wysokość ściany.', 'Użyj wymiarów wybranej rolki.', 'Sprawdź dopasowanie proste, przesunięte lub dowolne.', 'Kup tę samą partię, jeśli zaleca to producent.', 'Zaplanuj rolki na całą pracę.'] },
    ui: { configTitle: 'Zaplanuj ścianę', configSubtitle: 'Zamień wymiary na pełne rolki', unitSystemLabel: 'Jednostki', unitMetric: 'Metryczne', unitImperial: 'Anglosaskie', roomTitle: 'Ściana do pokrycia', labelRoomWidth: 'Całkowita szerokość ściany', labelWallHeight: 'Gotowa wysokość ściany', rollTitle: 'Etykieta rolki', labelRollWidth: 'Szerokość rolki', labelRollLength: 'Długość rolki', patternTitle: 'Wzór i rezerwa', labelPatternRepeat: 'Raport wzoru', patternHint: 'Użyj pionowego raportu z etykiety. Dla tapety gładkiej wpisz 0.', labelWasteAllowance: 'Zapas na odpady', wasteHint: 'Zapas zmniejsza długość rolki używaną w planie. Stosuj zalecenie producenta.', unitCentimetres: 'cm', unitInches: 'cale', unitFeet: 'stopy', unitPercent: '%', resultTitle: 'Szacunkowy zakup', labelRollsNeeded: 'Pełne rolki', rollsNeededSuffix: 'do kupienia', labelDropsNeeded: 'Bryty na ścianie', labelDropsPerRoll: 'Bryty z rolki', labelCutLength: 'Cięcie na bryt', labelLeftover: 'Pozostałość po cięciu', visualBadge: 'Planowanie brytów', invalidMeasurements: 'Sprawdź wymiary i użyj wartości dodatnich.', rollTooShort: 'Ta rolka jest za krótka na jeden bryt przy obecnym wzorze i zapasie.', resetLabel: 'Resetuj przykład' },
  },
  ru: {
    slug: 'kalkulyator-rulonov-oboev', title: 'Калькулятор рулонов обоев', description: 'Рассчитайте количество рулонов обоев по размерам стены и рулона, раппорту рисунка и запасу на отходы.',
    faq: [{ question: 'Сколько рулонов обоев нужно?', answer: 'Введите ширину и высоту стены, а также ширину и длину рулона. Калькулятор посчитает вертикальные полотна, учтёт раппорт и определит число целых рулонов.' }, { question: 'Что такое раппорт?', answer: 'Это вертикальное расстояние, через которое рисунок повторяется. Длину каждого полотна округляют до целого раппорта, чтобы соседние полосы совпадали.' }, { question: 'Почему для обоев с рисунком нужно больше рулонов?', answer: 'Подгонка рисунка делает полотно длиннее стены. Из-за этого из одного рулона получается меньше полос.' }, { question: 'Какой запас на отходы выбрать?', answer: 'Используйте рекомендацию производителя. Для первого расчёта можно взять 10 процентов на ошибки резки, повреждения и небольшие остатки.' }, { question: 'Учитывает ли расчёт двери и окна?', answer: 'Нет. Для консервативной оценки используется вся ширина стены. Перед покупкой сравните результат с производителем или мастером.' }],
    howTo: [{ name: 'Измерьте стену', text: 'Введите общую ширину покрытия и готовую высоту стены в сантиметрах.' }, { name: 'Прочитайте этикетку', text: 'Введите ширину и полную длину рулона с этикетки товара.' }, { name: 'Добавьте раппорт', text: 'Введите вертикальный раппорт. Для однотонных обоев без подгонки используйте ноль.' }, { name: 'Проверьте покупку', text: 'Сравните количество рулонов, полотен и остаток с инструкцией на товаре.' }],
    bibliographyNames: ['Erfurt: Как поклеить обои за 5 шагов', 'Graham & Brown: Как клеить обои', 'Wallpaperdirect: Руководство по оклейке стен'],
    seo: { introTitle: 'Превратите размеры стены в решение о покупке', introParagraph: 'Обои продаются целыми рулонами, а стены закрываются вертикальными полотнами. Важно понять, сколько полотен войдёт в рулон после подгонки по раппорту.', plainTitle: 'Обои без раппорта', plainDescription: 'Без повторяющегося рисунка каждое полотно режут по высоте стены, а длину рулона делят на полные полотна.', plainPoints: ['Установите раппорт 0 см', 'Длина резки равна высоте стены', 'Обрезки иногда можно использовать'], patternedTitle: 'Обои с рисунком', patternedDescription: 'Повторяющийся рисунок требует закончить каждое полотно в совпадающей точке. Калькулятор округляет длину до расчёта вместимости рулона.', patternedPoints: ['Сверьте раппорт с этикеткой', 'Совместите все полотна', 'Учитывайте дополнительную длину как остаток'], meaningTitle: 'Как понять результат', meaningParagraph: '<strong>Нужные рулоны</strong> — это число целых рулонов для покупки. <strong>Нужные полотна</strong> — вертикальные полосы стены. <strong>Длина резки</strong> учитывает рисунок, а <strong>остаток</strong> — общая длина после резки.', warningTitle: 'Главным остаётся ярлык товара', warningBadge: 'Важное ограничение', warningHtml: '<p>Производитель может указать способ подгонки, ограничения партии или дополнительный запас. Эта оценка не заменяет этикетку и совет мастера.</p>', summaryTitle: 'Перед покупкой', summaryItems: ['Измерьте готовую высоту стены.', 'Используйте размеры выбранного рулона.', 'Проверьте прямую, смещённую или свободную подгонку.', 'При необходимости купите одну партию.', 'Возьмите достаточно рулонов на всю работу.'] },
    ui: { configTitle: 'План стены', configSubtitle: 'Переведите размеры в целые рулоны', unitSystemLabel: 'Единицы', unitMetric: 'Метрические', unitImperial: 'Имперские', roomTitle: 'Стена для оклейки', labelRoomWidth: 'Полная ширина стены', labelWallHeight: 'Готовая высота стены', rollTitle: 'Этикетка рулона', labelRollWidth: 'Ширина рулона', labelRollLength: 'Длина рулона', patternTitle: 'Рисунок и запас', labelPatternRepeat: 'Раппорт рисунка', patternHint: 'Используйте вертикальный раппорт с этикетки. Для однотонных обоев укажите 0.', labelWasteAllowance: 'Запас на отходы', wasteHint: 'Запас уменьшает длину рулона для планирования. Следуйте рекомендации производителя.', unitCentimetres: 'см', unitInches: 'дюймы', unitFeet: 'футы', unitPercent: '%', resultTitle: 'Оценка покупки', labelRollsNeeded: 'Целые рулоны', rollsNeededSuffix: 'к покупке', labelDropsNeeded: 'Полотна на стене', labelDropsPerRoll: 'Полотен с рулона', labelCutLength: 'Длина резки полотна', labelLeftover: 'Остаток после резки', visualBadge: 'План полотен', invalidMeasurements: 'Проверьте размеры и введите положительные значения.', rollTooShort: 'Этого рулона недостаточно для одного полотна при текущем рисунке и запасе.', resetLabel: 'Сбросить пример' },
  },
  sv: {
    slug: 'tapetrullekalkylator', title: 'Kalkylator för tapetrullar', description: 'Räkna ut hur många tapetrullar du behöver utifrån väggens mått, rullens storlek, mönsterpassning och spillmarginal.',
    faq: [{ question: 'Hur många tapetrullar behöver jag?', answer: 'Ange väggens bredd och höjd samt rullens bredd och längd. Kalkylatorn räknar lodräta våder, tar hänsyn till mönsterpassningen och bestämmer antalet hela rullar.' }, { question: 'Vad betyder mönsterpassning?', answer: 'Det är det lodräta avståndet innan mönstret börjar om. Varje våd kapas till en multipel av detta mått så att intilliggande våder passar ihop.' }, { question: 'Varför går det åt fler rullar till mönstrad tapet?', answer: 'Mönsterpassningen kan göra varje våd längre än väggen. Den extra längden minskar antalet våder från varje rulle.' }, { question: 'Vilken spillmarginal ska jag använda?', answer: 'Följ tillverkarens rekommendation. Som första uppskattning kan 10% täcka kapfel, skador och småbitar.' }, { question: 'Räknas dörrar och fönster med?', answer: 'Nej. Hela väggbredden används för en försiktig uppskattning. Jämför resultatet med tillverkaren eller tapetseraren före köp.' }],
    howTo: [{ name: 'Mät väggen', text: 'Ange den totala bredden som ska täckas och den färdiga vägghöjden i centimeter.' }, { name: 'Läs rulletiketten', text: 'Ange rullens bredd och totala längd från produktetiketten.' }, { name: 'Lägg till mönsterpassning', text: 'Ange den lodräta passningen. Använd noll för enfärgad tapet utan mönsterpassning.' }, { name: 'Kontrollera köpet', text: 'Jämför rullar, våder och kvarvarande längd med produktens instruktioner.' }],
    bibliographyNames: ['Erfurt: Sätt upp tapet i fem steg', 'Graham & Brown: Så sätter du upp tapet', 'Wallpaperdirect: Guide för tapetsering'],
    seo: { introTitle: 'Gör väggmått till ett köpbeslut', introParagraph: 'Tapet säljs i hela rullar, men väggen täcks med lodräta våder. Den viktiga beräkningen är hur många våder som ryms i en rulle efter mönsterpassningen.', plainTitle: 'Enfärgad tapet', plainDescription: 'Utan mönsterpassning kapas varje våd efter vägghöjden och rullens längd delas i så många hela våder som möjligt.', plainPoints: ['Sätt passningen till 0 cm', 'Kaplängden är väggens höjd', 'Bitar kan vara användbara'], patternedTitle: 'Mönstrad tapet', patternedDescription: 'Ett upprepat mönster kräver att varje våd slutar på en matchande punkt. Kalkylatorn avrundar kapningen innan rullens kapacitet räknas.', patternedPoints: ['Läs passningen på etiketten', 'Passa ihop alla våder', 'Se extralängden som kvarvarande spill'], meaningTitle: 'Så läser du resultatet', meaningParagraph: '<strong>Rullar som behövs</strong> är antalet hela rullar att köpa. <strong>Våder som behövs</strong> är väggens lodräta remsor. <strong>Kaplängden</strong> innehåller mönsterpassningen och <strong>resten</strong> är längden efter kapning.', warningTitle: 'Produktetiketten gäller alltid', warningBadge: 'Viktig begränsning', warningHtml: '<p>Tillverkaren kan ange egna passningsmetoder, batchgränser eller extra marginal. Uppskattningen ersätter inte etiketten eller en yrkespersons råd.</p>', summaryTitle: 'Innan du köper', summaryItems: ['Mät den färdiga vägghöjden.', 'Använd måtten från den valda rullen.', 'Kontrollera rak, förskjuten eller fri mönsterpassning.', 'Välj samma batch om tillverkaren rekommenderar det.', 'Planera tillräckligt många rullar för hela arbetet.'] },
    ui: { configTitle: 'Planera väggen', configSubtitle: 'Förvandla mått till hela rullar', unitSystemLabel: 'Enheter', unitMetric: 'Metriskt', unitImperial: 'Imperialt', roomTitle: 'Vägg som ska täckas', labelRoomWidth: 'Total väggbredd', labelWallHeight: 'Färdig vägghöjd', rollTitle: 'Rulletikett', labelRollWidth: 'Rullbredd', labelRollLength: 'Rullängd', patternTitle: 'Mönster och reserv', labelPatternRepeat: 'Mönsterpassning', patternHint: 'Använd den lodräta passningen på etiketten. Sätt 0 för enfärgad eller fri passning.', labelWasteAllowance: 'Spillmarginal', wasteHint: 'Marginalen minskar den rullängd som används i planeringen. Följ tillverkarens råd.', unitCentimetres: 'cm', unitInches: 'tum', unitFeet: 'fot', unitPercent: '%', resultTitle: 'Din köpuppskattning', labelRollsNeeded: 'Hela rullar', rollsNeededSuffix: 'att köpa', labelDropsNeeded: 'Våder på väggen', labelDropsPerRoll: 'Våder per rulle', labelCutLength: 'Kaplängd per våd', labelLeftover: 'Längd kvar efter kapning', visualBadge: 'Vådplanering', invalidMeasurements: 'Kontrollera måtten och använd positiva värden.', rollTooShort: 'Rullen är för kort för en våd med aktuell mönsterpassning och reserv.', resetLabel: 'Återställ exempel' },
  },
  tr: {
    slug: 'duvar-kagidi-rulo-hesaplayici', title: 'Duvar Kağıdı Rulo Hesaplayıcı', description: 'Duvar ölçüsü, rulo boyutları, desen tekrarı ve fire payına göre kaç rulo duvar kağıdı gerektiğini hesaplayın.',
    faq: [{ question: 'Kaç rulo duvar kağıdına ihtiyacım var?', answer: 'Duvarın genişlik ve yüksekliğiyle rulo genişlik ve uzunluğunu girin. Hesaplayıcı dikey şeritleri, desen tekrarını ve tam rulo sayısını belirler.' }, { question: 'Desen tekrarı ne demektir?', answer: 'Desenin yeniden başlamasına kadar olan dikey mesafedir. Yan şeritlerin deseni tutması için her şerit bu ölçünün katı olacak şekilde kesilir.' }, { question: 'Desenli kağıt neden daha fazla rulo gerektirebilir?', answer: 'Deseni hizalamak her şeridi duvar yüksekliğinden uzun yapabilir. Bu ek uzunluk bir rulodan çıkan şerit sayısını azaltır.' }, { question: 'Ne kadar fire payı kullanmalıyım?', answer: 'Varsa üreticinin önerisini kullanın. İlk tahmin için kesim hataları, hasar ve küçük parçalar adına %10 pratik bir başlangıçtır.' }, { question: 'Kapı ve pencereler hesaba katılıyor mu?', answer: 'Hayır. Temkinli bir tahmin için duvarın tamamı kullanılır. Satın almadan önce sonucu üretici veya ustanın önerisiyle karşılaştırın.' }],
    howTo: [{ name: 'Duvarı ölçün', text: 'Kaplanacak toplam genişliği ve bitmiş duvar yüksekliğini santimetre olarak girin.' }, { name: 'Rulo etiketini okuyun', text: 'Ürün etiketindeki rulo genişliğini ve toplam uzunluğu girin.' }, { name: 'Desen tekrarını ekleyin', text: 'Dikey tekrar ölçüsünü girin. Düz veya eşleştirme gerektirmeyen kağıt için sıfır kullanın.' }, { name: 'Satın alma kararını kontrol edin', text: 'Rulo, şerit ve kalan uzunluk sonucunu ürün talimatlarıyla karşılaştırın.' }],
    bibliographyNames: ['Erfurt: Duvar kağıdı uygulama için 5 adım', 'Graham & Brown: Duvar kağıdı nasıl uygulanır', 'Wallpaperdirect: Duvar kağıdı uygulama rehberi'],
    seo: { introTitle: 'Duvar ölçüsünü satın alma kararına dönüştürün', introParagraph: 'Duvar kağıdı tam rulolarla satılır, ancak duvarlar dikey şeritlerle kaplanır. Önemli hesap, her kesimi desen tekrarına uyarladıktan sonra bir ruloya kaç şerit sığdığıdır.', plainTitle: 'Düz duvar kağıdı', plainDescription: 'Eşleştirilecek desen yoksa her şerit duvar yüksekliğine göre kesilir ve rulo uzunluğu tam şeritlere bölünür.', plainPoints: ['Tekrarı 0 cm yapın', 'Kesim uzunluğu duvar yüksekliğidir', 'Parçalar türüne göre kullanılabilir'], patternedTitle: 'Desenli duvar kağıdı', patternedDescription: 'Tekrarlanan desen her şeridin uyumlu bir noktada bitmesini gerektirir. Hesaplayıcı rulo kapasitesinden önce kesim uzunluğunu yukarı yuvarlar.', patternedPoints: ['Tekrarı etiketten okuyun', 'Her şeridi hizalayın', 'Ek uzunluğu kalan olarak görün'], meaningTitle: 'Sonucu anlama', meaningParagraph: '<strong>Gerekli rulolar</strong> satın alınacak tam rulo sayısıdır. <strong>Gerekli şeritler</strong> duvardaki dikey parçalardır. <strong>Kesim uzunluğu</strong> desen hizalamasını içerir, <strong>kalan</strong> ise kesimden sonraki brüt uzunluktur.', warningTitle: 'Son söz ürün etiketinindir', warningBadge: 'Önemli sınır', warningHtml: '<p>Üretici desen eşleştirme yöntemi, parti sınırı veya ek pay belirleyebilir. Bu tahmin etiketin ya da ustanın tavsiyesinin yerine geçmez.</p>', summaryTitle: 'Satın almadan önce', summaryItems: ['Bitmiş duvar yüksekliğini ölçün.', 'Seçtiğiniz rulonun etiket ölçülerini kullanın.', 'Düz, şaşırtmalı veya serbest deseni kontrol edin.', 'Üretici öneriyorsa aynı partiyi alın.', 'Tüm iş için yeterli rulo planlayın.'] },
    ui: { configTitle: 'Duvarı planlayın', configSubtitle: 'Ölçüleri tam rulo sayısına çevirin', unitSystemLabel: 'Birimler', unitMetric: 'Metrik', unitImperial: 'İngiliz', roomTitle: 'Kaplanacak duvar', labelRoomWidth: 'Toplam duvar genişliği', labelWallHeight: 'Bitmiş duvar yüksekliği', rollTitle: 'Rulo etiketi', labelRollWidth: 'Rulo genişliği', labelRollLength: 'Rulo uzunluğu', patternTitle: 'Desen ve pay', labelPatternRepeat: 'Desen tekrarı', patternHint: 'Etiketteki dikey tekrar ölçüsünü kullanın. Düz veya serbest desen için 0 girin.', labelWasteAllowance: 'Fire payı', wasteHint: 'Bu pay planlamada kullanılacak rulo uzunluğunu azaltır. Üretici önerisini izleyin.', unitCentimetres: 'cm', unitInches: 'inç', unitFeet: 'fit', unitPercent: '%', resultTitle: 'Satın alma tahmininiz', labelRollsNeeded: 'Tam rulolar', rollsNeededSuffix: 'satın alınacak', labelDropsNeeded: 'Duvardaki şeritler', labelDropsPerRoll: 'Rulo başına şerit', labelCutLength: 'Şerit başına kesim', labelLeftover: 'Kesim sonrası kalan', visualBadge: 'Şerit planı', invalidMeasurements: 'Ölçüleri kontrol edin ve pozitif değerler kullanın.', rollTooShort: 'Bu rulo mevcut desen ve pay ile bir şerit için çok kısa.', resetLabel: 'Örneği sıfırla' },
  },
  zh: {
    slug: 'bizhi-juanji-jisuanqi', title: '壁纸卷数计算器', description: '根据墙面尺寸、壁纸卷规格、图案重复和损耗余量，计算需要购买的壁纸卷数。',
    faq: [{ question: '我需要多少卷壁纸？', answer: '输入墙面的宽度和高度，以及壁纸卷的宽度和长度。计算器会考虑图案重复，计算竖向墙纸条数和完整卷数。' }, { question: '图案重复是什么意思？', answer: '这是图案再次出现前的竖向距离。为了让相邻墙纸条纹对齐，每条墙纸都要按重复距离的整数倍裁切。' }, { question: '为什么有图案的壁纸需要更多卷？', answer: '图案对齐会让每条墙纸比墙高更长，多出的长度会减少一卷中可以裁出的墙纸条数。' }, { question: '损耗余量应该设置多少？', answer: '优先遵循制造商建议。第一次估算可以使用10%，用于覆盖裁切错误、损坏和少量边角料。' }, { question: '计算会扣除门窗吗？', answer: '不会。为了得到保守估算，计算器使用整面墙的宽度。购买前请再参考制造商或施工人员的建议。' }],
    howTo: [{ name: '测量墙面', text: '输入需要覆盖的总宽度和完成后的墙面高度，单位为厘米。' }, { name: '查看壁纸标签', text: '输入产品标签上的壁纸卷宽度和总长度。' }, { name: '输入图案重复', text: '输入竖向重复距离。纯色壁纸或无需对花时输入0。' }, { name: '检查购买数量', text: '购买前，将卷数、墙纸条数和裁切后的剩余长度与产品说明比较。' }],
    bibliographyNames: ['Erfurt：五步完成壁纸施工', 'Graham & Brown：壁纸铺贴方法', 'Wallpaperdirect：壁纸施工指南'],
    seo: { introTitle: '把墙面尺寸转成购买决定', introParagraph: '壁纸按完整卷出售，而墙面由竖向墙纸条覆盖。关键是完成图案重复调整后，一卷壁纸可以裁出多少条。', plainTitle: '纯色壁纸', plainDescription: '没有需要对齐的图案时，每条墙纸按墙高裁切，再用卷长计算可以得到的完整条数。', plainPoints: ['将图案重复设为0厘米', '裁切长度等于墙面高度', '边角料可能仍然可以使用'], patternedTitle: '有图案的壁纸', patternedDescription: '重复图案要求每条墙纸在对应位置结束。计算器会在计算卷容量前向上调整裁切长度。', patternedPoints: ['从标签读取重复距离', '让每条墙纸图案对齐', '把额外长度作为剩余量查看'], meaningTitle: '如何理解结果', meaningParagraph: '<strong>需要的卷数</strong>是要购买的完整壁纸卷数。<strong>需要的墙纸条数</strong>是墙面的竖向条数。<strong>裁切长度</strong>包含图案对齐，<strong>剩余长度</strong>是裁切后的总剩余。', warningTitle: '最终以产品标签为准', warningBadge: '重要限制', warningHtml: '<p>制造商可能规定对花方式、批次限制或额外余量。这个估算不能替代产品标签或专业施工建议。</p>', summaryTitle: '购买前确认', summaryItems: ['测量完成后的墙面高度。', '使用所选壁纸卷标签上的规格。', '确认是直对花、错位对花还是自由铺贴。', '制造商建议时购买同一批次。', '为整个项目准备足够的壁纸卷。'] },
    ui: { configTitle: '规划墙面', configSubtitle: '将尺寸换算为完整壁纸卷', unitSystemLabel: '单位', unitMetric: '公制', unitImperial: '英制', roomTitle: '需要覆盖的墙面', labelRoomWidth: '墙面总宽度', labelWallHeight: '完成后的墙高', rollTitle: '壁纸卷标签', labelRollWidth: '壁纸卷宽度', labelRollLength: '壁纸卷长度', patternTitle: '图案和余量', labelPatternRepeat: '图案重复', patternHint: '使用标签上的竖向重复距离。纯色或自由铺贴输入0。', labelWasteAllowance: '损耗余量', wasteHint: '该余量会减少规划时使用的卷长。优先遵循制造商建议。', unitCentimetres: '厘米', unitInches: '英寸', unitFeet: '英尺', unitPercent: '%', resultTitle: '购买估算', labelRollsNeeded: '完整壁纸卷', rollsNeededSuffix: '需要购买', labelDropsNeeded: '墙面墙纸条数', labelDropsPerRoll: '每卷墙纸条数', labelCutLength: '每条裁切长度', labelLeftover: '裁切后剩余长度', visualBadge: '墙纸条规划', invalidMeasurements: '请检查尺寸并使用正数。', rollTooShort: '按当前图案和余量，这一卷不足以裁出一条墙纸。', resetLabel: '重置示例' },
  },
  de: {
    slug: 'tapetenrollen-rechner', title: 'Tapetenrollen-Rechner', description: 'Berechne, wie viele Tapetenrollen du anhand von Wandmass, Rollenmass, Rapport und Verschnitt brauchst.',
    faq: [
      { question: 'Wie viele Tapetenrollen brauche ich?', answer: 'Gib Wandbreite und -höhe sowie Rollenbreite und -länge ein. Der Rechner ermittelt Bahnen, berücksichtigt den Rapport und zählt vollständige Rollen.' },
      { question: 'Was bedeutet Rapport?', answer: 'Der Rapport ist der vertikale Abstand, nach dem sich das Muster wiederholt. Jede Bahn wird auf ein ganzes Rapportmass aufgerundet, damit die Muster zusammenpassen.' },
      { question: 'Warum braucht Mustertapete mehr Rollen?', answer: 'Durch das Anpassen an das Muster werden die Bahnen oft länger als die Wandhöhe. Dieser Mehrverbrauch wird zu Verschnitt und verringert die Bahnen pro Rolle.' },
      { question: 'Welche Verschnittreserve soll ich verwenden?', answer: 'Nutze die Empfehlung des Herstellers. Für eine erste Schätzung sind 10 Prozent ein sinnvoller Ausgangspunkt für Zuschnittfehler und kleine Reste.' },
      { question: 'Berücksichtigt der Rechner Türen und Fenster?', answer: 'Nein. Die volle Wandbreite ergibt eine konservative Schätzung. Vergleiche das Ergebnis vor dem Kauf mit Herstellerangaben oder dem Rat eines Fachbetriebs.' },
    ],
    howTo: [{ name: 'Wand messen', text: 'Gib die gesamte zu tapezierende Breite und die fertige Wandhöhe in Zentimetern ein.' }, { name: 'Rollenetikett lesen', text: 'Übernimm Rollenbreite und Gesamtlänge vom Produktetikett.' }, { name: 'Rapport eintragen', text: 'Gib den vertikalen Rapport ein. Für ungemusterte Tapete verwendest du null.' }, { name: 'Kaufentscheidung prüfen', text: 'Vergleiche Rollenanzahl, Bahnen und Restlänge mit den Herstellerangaben.' }],
    bibliographyNames: ['Erfurt: Rauhfaser tapezieren in 5 Schritten', 'Graham & Brown: Tapeten richtig anbringen', 'Wallpaperdirect: Anleitung zum Tapezieren'],
    seo: { introTitle: 'Wandmasse in eine Kaufentscheidung übersetzen', introParagraph: 'Tapeten werden in ganzen Rollen verkauft, Wände aber mit senkrechten Bahnen tapeziert. Entscheidend ist, wie viele Bahnen nach der Aufrundung auf den Rapport in eine Rolle passen.', plainTitle: 'Tapete ohne Rapport', plainDescription: 'Ohne Musterwiederholung entspricht die Schnittlänge der Wandhöhe und die Rollenlänge wird in möglichst viele ganze Bahnen geteilt.', plainPoints: ['Rapport auf 0 cm setzen', 'Schnittlänge entspricht der Wandhöhe', 'Reste können je nach Tapete weiter nutzbar sein'], patternedTitle: 'Mustertapete', patternedDescription: 'Bei einem wiederkehrenden Muster muss jede Bahn an einem passenden Punkt enden. Der Rechner rundet die Länge vor der Kapazitätsberechnung auf.', patternedPoints: ['Rapport vom Etikett übernehmen', 'Jede Bahn am Muster ausrichten', 'Mehrlänge als Rest einplanen'], meaningTitle: 'Was das Ergebnis bedeutet', meaningParagraph: '<strong>Benötigte Rollen</strong> ist die Anzahl ganzer Rollen. <strong>Benötigte Bahnen</strong> sind die senkrechten Streifen an der Wand. Die <strong>Schnittlänge</strong> enthält die Musteranpassung. Der <strong>Rest</strong> ist die verbleibende Bruttolänge.', warningTitle: 'Das Produktetikett ist massgeblich', warningBadge: 'Wichtige Grenze', warningHtml: '<p>Hersteller können eigene Musterregeln, Chargenhinweise oder zusätzliche Reserven vorgeben. Diese Schätzung ersetzt weder das Etikett noch die Beratung eines Tapezierers.</p>', summaryTitle: 'Vor dem Kauf', summaryItems: ['Fertige Wandhöhe messen.', 'Breite und Länge der konkreten Rolle verwenden.', 'Geraden, versetzten oder ansatzfreien Rapport prüfen.', 'Bei Herstellerempfehlung dieselbe Charge kaufen.', 'Für das gesamte Projekt ausreichend Rollen einplanen.'] },
    ui: { configTitle: 'Wand planen', configSubtitle: 'Masse in ganze Rollen umrechnen', unitSystemLabel: 'Einheiten', unitMetric: 'Metrisch', unitImperial: 'Imperial', roomTitle: 'Zu tapezierende Wand', labelRoomWidth: 'Gesamte Wandbreite', labelWallHeight: 'Fertige Wandhöhe', rollTitle: 'Rollenetikett', labelRollWidth: 'Rollenbreite', labelRollLength: 'Rollenlänge', patternTitle: 'Rapport und Reserve', labelPatternRepeat: 'Rapport', patternHint: 'Vertikalen Rapport vom Etikett übernehmen. Für ungemusterte Tapete 0 setzen.', labelWasteAllowance: 'Verschnittreserve', wasteHint: 'Die Reserve reduziert die nutzbare Rollenlänge. Herstellerempfehlung beachten.', unitCentimetres: 'cm', unitInches: 'Zoll', unitFeet: 'ft', unitPercent: '%', resultTitle: 'Deine Kaufschätzung', labelRollsNeeded: 'Ganze Rollen', rollsNeededSuffix: 'zu kaufen', labelDropsNeeded: 'Bahnen an der Wand', labelDropsPerRoll: 'Bahnen pro Rolle', labelCutLength: 'Schnittlänge pro Bahn', labelLeftover: 'Rest nach Zuschnitt', visualBadge: 'Bahnplanung', invalidMeasurements: 'Masse prüfen und positive Werte verwenden.', rollTooShort: 'Diese Rolle reicht mit dem aktuellen Rapport und der Reserve nicht für eine Bahn.', resetLabel: 'Beispiel zurücksetzen' },
  },
  es: {
    slug: 'calculadora-rollos-papel-pintado', title: 'Calculadora de rollos de papel pintado', description: 'Calcula cuántos rollos de papel pintado necesitas según la pared, las medidas del rollo, el rapport y el desperdicio.',
    faq: [{ question: '¿Cuántos rollos de papel pintado necesito?', answer: 'Introduce el ancho y la altura de la pared, además del ancho y el largo del rollo. La calculadora convierte el ancho en paños verticales, ajusta cada paño al rapport y cuenta rollos completos.' }, { question: '¿Qué significa rapport?', answer: 'El rapport es la distancia vertical tras la que se repite el dibujo. Cada paño se corta a un múltiplo del rapport para que las tiras contiguas encajen.' }, { question: '¿Por qué un papel estampado puede necesitar más rollos?', answer: 'El ajuste del dibujo puede hacer que cada paño sea más largo que la pared. Ese sobrante reduce el número de paños que salen de cada rollo.' }, { question: '¿Qué desperdicio debo añadir?', answer: 'Usa la recomendación del fabricante. Como primera estimación, el 10 % cubre errores de corte, daños y pequeños retales.' }, { question: '¿Incluye puertas y ventanas?', answer: 'No. Usa todo el ancho de la pared para mantener una estimación prudente. Antes de comprar, compárala con el fabricante o un instalador.' }],
    howTo: [{ name: 'Mide la pared', text: 'Introduce el ancho total que cubrir y la altura terminada en centímetros.' }, { name: 'Lee la etiqueta', text: 'Introduce el ancho y el largo total indicados en la etiqueta del rollo.' }, { name: 'Añade el rapport', text: 'Introduce el rapport vertical. Usa cero si el papel es liso o no requiere casar el dibujo.' }, { name: 'Comprueba la compra', text: 'Compara rollos, paños y sobrante con las instrucciones del producto antes de comprar.' }],
    bibliographyNames: ['Erfurt: Cómo empapelar con papel pintado', 'Graham & Brown: Cómo colocar papel pintado', 'Wallpaperdirect: Guía para colocar papel pintado'],
    seo: { introTitle: 'Convierte las medidas en una decisión de compra', introParagraph: 'El papel pintado se vende en rollos completos, pero las paredes se cubren con paños verticales. La clave es saber cuántos paños caben en un rollo después de ajustar cada corte al rapport.', plainTitle: 'Papel sin rapport', plainDescription: 'Sin repetición del dibujo, cada paño se corta a la altura de la pared y el largo del rollo se divide en tantos paños completos como sea posible.', plainPoints: ['Pon el rapport a 0 cm', 'El corte coincide con la altura', 'Los retales pueden seguir siendo útiles'], patternedTitle: 'Papel estampado', patternedDescription: 'Un dibujo repetido exige que cada paño termine en un punto de coincidencia. La calculadora redondea el corte antes de contar la capacidad del rollo.', patternedPoints: ['Lee el rapport de la etiqueta', 'Alinea todos los paños', 'El sobrante muestra el coste del dibujo'], meaningTitle: 'Qué significa el resultado', meaningParagraph: '<strong>Rollos necesarios</strong> es el número de rollos completos que debes comprar. <strong>Paños necesarios</strong> son las tiras verticales de la pared. El <strong>largo de corte</strong> incluye el ajuste del dibujo y el <strong>sobrante</strong> es la longitud bruta que queda.', warningTitle: 'La etiqueta del producto manda', warningBadge: 'Límite importante', warningHtml: '<p>El fabricante puede indicar métodos de casar el dibujo, límites de lote o una reserva adicional. Esta es una estimación transparente, no sustituye la etiqueta ni el consejo de un instalador.</p>', summaryTitle: 'Antes de comprar', summaryItems: ['Mide la altura terminada de la pared.', 'Usa las medidas del rollo concreto.', 'Comprueba si el rapport es recto, salteado o libre.', 'Mantén el mismo lote cuando lo recomiende el fabricante.', 'Compra suficiente para toda la obra porque los lotes pueden variar.'] },
    ui: { configTitle: 'Planifica la pared', configSubtitle: 'Convierte medidas en rollos completos', unitSystemLabel: 'Unidades', unitMetric: 'Métrico', unitImperial: 'Imperial', roomTitle: 'Pared que cubrir', labelRoomWidth: 'Ancho total de pared', labelWallHeight: 'Altura terminada', rollTitle: 'Etiqueta del rollo', labelRollWidth: 'Ancho del rollo', labelRollLength: 'Largo del rollo', patternTitle: 'Rapport y reserva', labelPatternRepeat: 'Rapport', patternHint: 'Usa el rapport vertical de la etiqueta. Pon 0 para papel liso o de casar libre.', labelWasteAllowance: 'Reserva de desperdicio', wasteHint: 'Esta reserva reduce el largo útil del rollo. Sigue la recomendación del fabricante.', unitCentimetres: 'cm', unitInches: 'pulg', unitFeet: 'pies', unitPercent: '%', resultTitle: 'Tu estimación de compra', labelRollsNeeded: 'Rollos completos', rollsNeededSuffix: 'que comprar', labelDropsNeeded: 'Paños en la pared', labelDropsPerRoll: 'Paños por rollo', labelCutLength: 'Largo de corte por paño', labelLeftover: 'Sobrante tras cortar', visualBadge: 'Mesa de planificación', invalidMeasurements: 'Revisa las medidas y usa valores positivos.', rollTooShort: 'Este rollo no alcanza para un paño con el rapport y la reserva actuales.', resetLabel: 'Restablecer ejemplo' },
  },
  fr: {
    slug: 'calculateur-rouleaux-papier-peint', title: 'Calculateur de rouleaux de papier peint', description: 'Calculez le nombre de rouleaux nécessaires selon les dimensions du mur, du rouleau, le raccord et la marge de perte.',
    faq: [{ question: 'De combien de rouleaux ai-je besoin ?', answer: 'Saisissez la largeur et la hauteur du mur, puis la largeur et la longueur du rouleau. Le calculateur compte les lés verticaux, applique le raccord et détermine les rouleaux entiers.' }, { question: 'Que signifie le raccord ?', answer: 'Le raccord est la distance verticale après laquelle le motif se répète. Chaque lé est coupé sur un multiple du raccord afin d’aligner les bandes voisines.' }, { question: 'Pourquoi un papier peint à motif demande-t-il plus de rouleaux ?', answer: 'L’alignement du motif peut allonger chaque lé au-delà de la hauteur du mur. Cette longueur supplémentaire réduit le nombre de lés obtenus par rouleau.' }, { question: 'Quelle marge de perte utiliser ?', answer: 'Suivez la recommandation du fabricant. Pour une première estimation, 10 % couvrent les erreurs de coupe, les dommages et les petites chutes.' }, { question: 'Le calculateur tient-il compte des portes et fenêtres ?', answer: 'Non. Il utilise toute la largeur du mur pour rester prudent. Comparez ensuite le résultat avec le fabricant ou le poseur.' }],
    howTo: [{ name: 'Mesurer le mur', text: 'Saisissez la largeur totale à couvrir et la hauteur finie en centimètres.' }, { name: 'Lire l’étiquette', text: 'Saisissez la largeur et la longueur indiquées sur l’étiquette du rouleau.' }, { name: 'Ajouter le raccord', text: 'Saisissez le raccord vertical. Utilisez zéro pour un papier uni ou sans raccord.' }, { name: 'Vérifier l’achat', text: 'Comparez le nombre de rouleaux, de lés et la chute avec les instructions du produit.' }],
    bibliographyNames: ['Erfurt : poser du papier peint en cinq étapes', 'Graham & Brown : poser du papier peint', 'Wallpaperdirect : guide de pose du papier peint'],
    seo: { introTitle: 'Transformer les mesures en décision d’achat', introParagraph: 'Le papier peint est vendu en rouleaux entiers, mais les murs sont couverts de lés verticaux. L’essentiel est de savoir combien de lés entrent dans un rouleau après l’ajustement au raccord.', plainTitle: 'Papier uni', plainDescription: 'Sans motif à raccorder, chaque lé est coupé à la hauteur du mur et la longueur du rouleau est divisée en lés entiers.', plainPoints: ['Régler le raccord sur 0 cm', 'La coupe suit la hauteur du mur', 'Les chutes peuvent rester utiles'], patternedTitle: 'Papier à motif', patternedDescription: 'Un motif répétitif exige que chaque lé se termine sur un point correspondant. Le calculateur arrondit la coupe avant de compter la capacité.', patternedPoints: ['Lire le raccord sur l’étiquette', 'Aligner chaque lé', 'Visualiser la longueur perdue'], meaningTitle: 'Comprendre le résultat', meaningParagraph: 'Les <strong>rouleaux nécessaires</strong> sont les rouleaux entiers à acheter. Les <strong>lés nécessaires</strong> sont les bandes verticales du mur. La <strong>longueur de coupe</strong> intègre le raccord et la <strong>chute</strong> est la longueur brute restante.', warningTitle: 'L’étiquette du produit reste prioritaire', warningBadge: 'Limite importante', warningHtml: '<p>Le fabricant peut imposer une méthode de raccord, une limite de lot ou une marge supplémentaire. Cette estimation ne remplace ni l’étiquette ni l’avis d’un professionnel.</p>', summaryTitle: 'Avant d’acheter', summaryItems: ['Mesurez la hauteur finie du mur.', 'Utilisez les dimensions du rouleau choisi.', 'Vérifiez le raccord droit, sauté ou libre.', 'Conservez le même lot si le fabricant le conseille.', 'Prévoyez assez de rouleaux pour tout le chantier.'] },
    ui: { configTitle: 'Planifier le mur', configSubtitle: 'Transformer les mesures en rouleaux entiers', unitSystemLabel: 'Unités', unitMetric: 'Métrique', unitImperial: 'Impérial', roomTitle: 'Mur à couvrir', labelRoomWidth: 'Largeur totale du mur', labelWallHeight: 'Hauteur finie du mur', rollTitle: 'Étiquette du rouleau', labelRollWidth: 'Largeur du rouleau', labelRollLength: 'Longueur du rouleau', patternTitle: 'Raccord et réserve', labelPatternRepeat: 'Raccord', patternHint: 'Utilisez le raccord vertical indiqué sur l’étiquette. Mettez 0 pour un papier uni.', labelWasteAllowance: 'Marge de perte', wasteHint: 'Cette réserve réduit la longueur utile. Suivez la recommandation du fabricant.', unitCentimetres: 'cm', unitInches: 'po', unitFeet: 'pi', unitPercent: '%', resultTitle: 'Votre estimation d’achat', labelRollsNeeded: 'Rouleaux entiers', rollsNeededSuffix: 'à acheter', labelDropsNeeded: 'Lés sur le mur', labelDropsPerRoll: 'Lés par rouleau', labelCutLength: 'Coupe par lé', labelLeftover: 'Reste après coupe', visualBadge: 'Table de planification', invalidMeasurements: 'Vérifiez les mesures et utilisez des valeurs positives.', rollTooShort: 'Ce rouleau est trop court pour un lé avec le raccord et la marge actuels.', resetLabel: 'Réinitialiser l’exemple' },
  },
  id: {
    slug: 'kalkulator-gulungan-wallpaper', title: 'Kalkulator Gulungan Wallpaper', description: 'Hitung jumlah gulungan wallpaper berdasarkan ukuran dinding, ukuran gulungan, pengulangan pola, dan cadangan limbah.',
    faq: [{ question: 'Berapa gulungan wallpaper yang saya perlukan?', answer: 'Masukkan lebar dan tinggi dinding serta lebar dan panjang gulungan. Kalkulator menghitung lajur vertikal, menyesuaikan pengulangan pola, lalu menentukan gulungan utuh.' }, { question: 'Apa arti pengulangan pola?', answer: 'Pengulangan pola adalah jarak vertikal sebelum desain berulang. Setiap lajur dipotong sebagai kelipatan jarak itu agar pola antar lajur menyatu.' }, { question: 'Mengapa wallpaper bermotif membutuhkan lebih banyak gulungan?', answer: 'Penyesuaian pola dapat membuat setiap lajur lebih panjang dari tinggi dinding. Panjang tambahan ini mengurangi jumlah lajur dari satu gulungan.' }, { question: 'Berapa cadangan limbah yang sebaiknya digunakan?', answer: 'Ikuti rekomendasi produsen. Untuk perkiraan awal, 10% membantu menutup kesalahan potong, kerusakan, dan sisa kecil.' }, { question: 'Apakah pintu dan jendela dihitung?', answer: 'Tidak. Lebar dinding penuh digunakan agar perkiraan tetap konservatif. Bandingkan hasilnya dengan produsen atau pemasang sebelum membeli.' }],
    howTo: [{ name: 'Ukur dinding', text: 'Masukkan lebar total yang akan ditutup dan tinggi dinding akhir dalam sentimeter.' }, { name: 'Baca label gulungan', text: 'Masukkan lebar dan panjang total yang tercetak pada label produk.' }, { name: 'Tambahkan pengulangan pola', text: 'Masukkan pengulangan vertikal. Gunakan nol untuk wallpaper polos tanpa pencocokan pola.' }, { name: 'Periksa keputusan pembelian', text: 'Bandingkan jumlah gulungan, lajur, dan sisa dengan petunjuk produk.' }],
    bibliographyNames: ['Erfurt: Cara memasang wallpaper dalam lima langkah', 'Graham & Brown: Cara memasang wallpaper', 'Wallpaperdirect: Panduan memasang wallpaper'],
    seo: { introTitle: 'Ubah ukuran dinding menjadi keputusan pembelian', introParagraph: 'Wallpaper dijual dalam gulungan utuh, sementara dinding ditutup oleh lajur vertikal. Perhitungan pentingnya adalah jumlah lajur yang muat setelah setiap potongan disesuaikan dengan pengulangan pola.', plainTitle: 'Wallpaper polos', plainDescription: 'Tanpa pola berulang, setiap lajur dipotong sesuai tinggi dinding dan panjang gulungan dibagi menjadi lajur utuh sebanyak mungkin.', plainPoints: ['Atur pengulangan ke 0 cm', 'Panjang potong sama dengan tinggi dinding', 'Sisa dapat digunakan jika jenis wallpaper memungkinkan'], patternedTitle: 'Wallpaper bermotif', patternedDescription: 'Pola berulang mengharuskan setiap lajur berakhir pada titik yang cocok. Kalkulator membulatkan potongan sebelum menghitung kapasitas gulungan.', patternedPoints: ['Baca pengulangan dari label', 'Selaraskan setiap lajur', 'Lihat panjang tambahan sebagai sisa'], meaningTitle: 'Arti hasilnya', meaningParagraph: '<strong>Gulungan yang diperlukan</strong> adalah jumlah gulungan utuh yang dibeli. <strong>Lajur yang diperlukan</strong> adalah strip vertikal pada dinding. <strong>Panjang potong</strong> mencakup penyesuaian pola, sedangkan <strong>sisa</strong> adalah panjang kotor yang tersisa.', warningTitle: 'Label produk tetap menjadi acuan utama', warningBadge: 'Batas penting', warningHtml: '<p>Produsen dapat menetapkan cara pencocokan, batas batch, atau cadangan tambahan. Perkiraan ini bukan pengganti label atau saran pemasang.</p>', summaryTitle: 'Sebelum membeli', summaryItems: ['Ukur tinggi akhir dinding.', 'Gunakan ukuran pada label gulungan yang dipilih.', 'Periksa pola lurus, jatuh, atau bebas.', 'Gunakan batch yang sama jika disarankan produsen.', 'Siapkan gulungan yang cukup untuk seluruh pekerjaan.'] },
    ui: { configTitle: 'Rencanakan dinding', configSubtitle: 'Ubah ukuran menjadi gulungan utuh', unitSystemLabel: 'Satuan', unitMetric: 'Metrik', unitImperial: 'Imperial', roomTitle: 'Dinding yang ditutup', labelRoomWidth: 'Lebar total dinding', labelWallHeight: 'Tinggi akhir dinding', rollTitle: 'Label gulungan', labelRollWidth: 'Lebar gulungan', labelRollLength: 'Panjang gulungan', patternTitle: 'Pola dan cadangan', labelPatternRepeat: 'Pengulangan pola', patternHint: 'Gunakan pengulangan vertikal pada label. Isi 0 untuk wallpaper polos.', labelWasteAllowance: 'Cadangan limbah', wasteHint: 'Cadangan ini mengurangi panjang gulungan yang digunakan. Ikuti saran produsen.', unitCentimetres: 'cm', unitInches: 'inci', unitFeet: 'kaki', unitPercent: '%', resultTitle: 'Perkiraan pembelian', labelRollsNeeded: 'Gulungan utuh', rollsNeededSuffix: 'untuk dibeli', labelDropsNeeded: 'Lajur pada dinding', labelDropsPerRoll: 'Lajur per gulungan', labelCutLength: 'Panjang potong per lajur', labelLeftover: 'Sisa setelah dipotong', visualBadge: 'Meja perencanaan lajur', invalidMeasurements: 'Periksa ukuran dan gunakan nilai positif.', rollTooShort: 'Gulungan ini terlalu pendek untuk satu lajur dengan pola dan cadangan saat ini.', resetLabel: 'Atur ulang contoh' },
  },
  it: {
    slug: 'calcolatore-rotoli-carta-da-parati', title: 'Calcolatore dei rotoli di carta da parati', description: 'Calcola quanti rotoli servono in base alle misure della parete, del rotolo, al rapporto del motivo e allo sfrido.',
    faq: [{ question: 'Quanti rotoli di carta da parati mi servono?', answer: 'Inserisci larghezza e altezza della parete, larghezza e lunghezza del rotolo. Il calcolatore conta le strisce verticali, considera il rapporto del motivo e determina i rotoli interi.' }, { question: 'Che cos’è il rapporto del motivo?', answer: 'È la distanza verticale dopo la quale il disegno ricomincia. Ogni striscia viene tagliata su un multiplo del rapporto per allineare le strisce vicine.' }, { question: 'Perché una carta decorata può richiedere più rotoli?', answer: 'L’allineamento del motivo può rendere ogni striscia più lunga della parete. Questa lunghezza aggiuntiva riduce il numero di strisce ottenibili da un rotolo.' }, { question: 'Quale percentuale di sfrido devo usare?', answer: 'Segui la raccomandazione del produttore. Per una prima stima, il 10% copre errori di taglio, danni e piccoli ritagli.' }, { question: 'Il calcolatore considera porte e finestre?', answer: 'No. Usa tutta la larghezza della parete per mantenere una stima prudente. Confronta il risultato con il produttore o il posatore.' }],
    howTo: [{ name: 'Misura la parete', text: 'Inserisci la larghezza totale da coprire e l’altezza finita in centimetri.' }, { name: 'Leggi l’etichetta', text: 'Inserisci larghezza e lunghezza totale riportate sull’etichetta del rotolo.' }, { name: 'Aggiungi il rapporto', text: 'Inserisci il rapporto verticale. Usa zero per una carta semplice senza raccordo.' }, { name: 'Controlla l’acquisto', text: 'Confronta rotoli, strisce e avanzo con le istruzioni del prodotto.' }],
    bibliographyNames: ['Erfurt: Come applicare la carta da parati', 'Graham & Brown: Come applicare la carta da parati', 'Wallpaperdirect: Guida alla posa della carta da parati'],
    seo: { introTitle: 'Trasforma le misure in una decisione d’acquisto', introParagraph: 'La carta da parati si vende in rotoli interi, ma le pareti si coprono con strisce verticali. Il calcolo utile è quante strisce entrano in un rotolo dopo aver adattato ogni taglio al rapporto del motivo.', plainTitle: 'Carta senza rapporto', plainDescription: 'Senza un motivo da raccordare, ogni striscia viene tagliata all’altezza della parete e la lunghezza del rotolo viene divisa in strisce intere.', plainPoints: ['Imposta il rapporto a 0 cm', 'Il taglio segue l’altezza della parete', 'I ritagli possono restare utilizzabili'], patternedTitle: 'Carta decorata', patternedDescription: 'Un motivo ripetuto richiede che ogni striscia termini su un punto corrispondente. Il calcolatore arrotonda il taglio prima di contare la capacità.', patternedPoints: ['Leggi il rapporto sull’etichetta', 'Allinea ogni striscia', 'Considera la lunghezza extra come avanzo'], meaningTitle: 'Come leggere il risultato', meaningParagraph: '<strong>Rotoli necessari</strong> indica quanti rotoli interi acquistare. Le <strong>strisce necessarie</strong> sono le bande verticali della parete. La <strong>lunghezza di taglio</strong> include il raccordo e l’<strong>avanzo</strong> è la lunghezza lorda rimasta.', warningTitle: 'Fa fede l’etichetta del prodotto', warningBadge: 'Limite importante', warningHtml: '<p>Il produttore può indicare metodi di raccordo, limiti di lotto o una riserva aggiuntiva. Questa stima non sostituisce l’etichetta né il consiglio di un professionista.</p>', summaryTitle: 'Prima di acquistare', summaryItems: ['Misura l’altezza finita della parete.', 'Usa le misure del rotolo scelto.', 'Controlla raccordo diritto, sfalsato o libero.', 'Conserva lo stesso lotto se indicato dal produttore.', 'Prevedi abbastanza rotoli per tutto il lavoro.'] },
    ui: { configTitle: 'Pianifica la parete', configSubtitle: 'Trasforma le misure in rotoli interi', unitSystemLabel: 'Unità', unitMetric: 'Metrico', unitImperial: 'Imperiale', roomTitle: 'Parete da coprire', labelRoomWidth: 'Larghezza totale parete', labelWallHeight: 'Altezza finita parete', rollTitle: 'Etichetta del rotolo', labelRollWidth: 'Larghezza rotolo', labelRollLength: 'Lunghezza rotolo', patternTitle: 'Rapporto e riserva', labelPatternRepeat: 'Rapporto del motivo', patternHint: 'Usa il rapporto verticale dell’etichetta. Inserisci 0 per una carta senza raccordo.', labelWasteAllowance: 'Riserva di sfrido', wasteHint: 'La riserva riduce la lunghezza utile. Segui la raccomandazione del produttore.', unitCentimetres: 'cm', unitInches: 'pollici', unitFeet: 'piedi', unitPercent: '%', resultTitle: 'La tua stima d’acquisto', labelRollsNeeded: 'Rotoli interi', rollsNeededSuffix: 'da acquistare', labelDropsNeeded: 'Strisce sulla parete', labelDropsPerRoll: 'Strisce per rotolo', labelCutLength: 'Taglio per striscia', labelLeftover: 'Avanzo dopo i tagli', visualBadge: 'Tavolo di pianificazione', invalidMeasurements: 'Controlla le misure e usa valori positivi.', rollTooShort: 'Questo rotolo è troppo corto per una striscia con il rapporto e la riserva attuali.', resetLabel: 'Ripristina esempio' },
  },
  pt: {
    slug: 'calculadora-rolos-papel-parede', title: 'Calculadora de rolos de papel de parede', description: 'Calcule quantos rolos de papel de parede precisa com base na parede, nas medidas do rolo, no rapport e na margem de desperdício.',
    faq: [{ question: 'De quantos rolos de papel de parede preciso?', answer: 'Indique a largura e a altura da parede, além da largura e do comprimento do rolo. A calculadora conta as faixas verticais, ajusta o rapport e determina os rolos completos.' }, { question: 'O que significa rapport?', answer: 'É a distância vertical até o desenho se repetir. Cada faixa é cortada num múltiplo do rapport para alinhar as faixas vizinhas.' }, { question: 'Porque é que um papel estampado pode precisar de mais rolos?', answer: 'O alinhamento do desenho pode tornar cada faixa mais comprida do que a parede. Esse comprimento extra reduz o número de faixas por rolo.' }, { question: 'Que margem de desperdício devo usar?', answer: 'Siga a recomendação do fabricante. Para uma primeira estimativa, 10% cobrem erros de corte, danos e pequenos restos.' }, { question: 'A calculadora considera portas e janelas?', answer: 'Não. Usa a largura total da parede para manter uma estimativa conservadora. Compare o resultado com o fabricante ou instalador.' }],
    howTo: [{ name: 'Meça a parede', text: 'Introduza a largura total a cobrir e a altura final em centímetros.' }, { name: 'Leia a etiqueta', text: 'Introduza a largura e o comprimento total indicados na etiqueta do rolo.' }, { name: 'Adicione o rapport', text: 'Introduza o rapport vertical. Use zero para papel liso ou sem necessidade de casar o desenho.' }, { name: 'Confirme a compra', text: 'Compare rolos, faixas e sobra com as instruções do produto.' }],
    bibliographyNames: ['Erfurt: Como aplicar papel de parede', 'Graham & Brown: Como aplicar papel de parede', 'Wallpaperdirect: Guia para aplicar papel de parede'],
    seo: { introTitle: 'Transforme medidas numa decisão de compra', introParagraph: 'O papel de parede é vendido em rolos completos, mas as paredes são cobertas com faixas verticais. O cálculo útil é quantas faixas cabem num rolo depois de ajustar cada corte ao rapport.', plainTitle: 'Papel sem rapport', plainDescription: 'Sem repetição do desenho, cada faixa é cortada à altura da parede e o comprimento do rolo é dividido em faixas completas.', plainPoints: ['Defina o rapport como 0 cm', 'O corte acompanha a altura da parede', 'As sobras podem continuar úteis'], patternedTitle: 'Papel estampado', patternedDescription: 'Um desenho repetido exige que cada faixa termine num ponto de correspondência. A calculadora arredonda o corte antes de calcular a capacidade.', patternedPoints: ['Leia o rapport na etiqueta', 'Alinhe todas as faixas', 'Considere o comprimento extra como sobra'], meaningTitle: 'O que significa o resultado', meaningParagraph: '<strong>Rolos necessários</strong> é o número de rolos completos a comprar. <strong>Faixas necessárias</strong> são as tiras verticais da parede. O <strong>comprimento de corte</strong> inclui o alinhamento e a <strong>sobra</strong> é o comprimento bruto restante.', warningTitle: 'A etiqueta do produto é a autoridade final', warningBadge: 'Limite importante', warningHtml: '<p>O fabricante pode indicar métodos de alinhamento, limites de lote ou uma margem adicional. Esta estimativa não substitui a etiqueta nem o conselho de um profissional.</p>', summaryTitle: 'Antes de comprar', summaryItems: ['Meça a altura final da parede.', 'Use as medidas do rolo escolhido.', 'Confirme se o rapport é reto, desencontrado ou livre.', 'Mantenha o mesmo lote quando recomendado.', 'Compre rolos suficientes para todo o trabalho.'] },
    ui: { configTitle: 'Planeie a parede', configSubtitle: 'Converta medidas em rolos completos', unitSystemLabel: 'Unidades', unitMetric: 'Métrico', unitImperial: 'Imperial', roomTitle: 'Parede a cobrir', labelRoomWidth: 'Largura total da parede', labelWallHeight: 'Altura final da parede', rollTitle: 'Etiqueta do rolo', labelRollWidth: 'Largura do rolo', labelRollLength: 'Comprimento do rolo', patternTitle: 'Rapport e reserva', labelPatternRepeat: 'Rapport', patternHint: 'Use o rapport vertical da etiqueta. Defina 0 para papel liso ou sem encaixe.', labelWasteAllowance: 'Margem de desperdício', wasteHint: 'Esta margem reduz o comprimento útil. Siga a recomendação do fabricante.', unitCentimetres: 'cm', unitInches: 'pol', unitFeet: 'pés', unitPercent: '%', resultTitle: 'A sua estimativa de compra', labelRollsNeeded: 'Rolos completos', rollsNeededSuffix: 'a comprar', labelDropsNeeded: 'Faixas na parede', labelDropsPerRoll: 'Faixas por rolo', labelCutLength: 'Corte por faixa', labelLeftover: 'Sobra após cortes', visualBadge: 'Mesa de planeamento', invalidMeasurements: 'Verifique as medidas e use valores positivos.', rollTooShort: 'Este rolo é demasiado curto para uma faixa com o rapport e a margem atuais.', resetLabel: 'Repor exemplo' },
  },
};
