import type { WithContext, FAQPage, HowTo, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { SolarBatteryAutonomyCalculatorUI } from '../ui';
import { bibliography } from '../bibliography';

type Pack = {
  slug: string; title: string; description: string; ui: SolarBatteryAutonomyCalculatorUI;
  faq: { question: string; answer: string }[];
  howTo: { name: string; text: string }[];
  sections: [string, string, string, string, string, string, string, string];
  compare: [{ title: string; description: string; points: string[] }, { title: string; description: string; points: string[] }];
};

const iconA = 'mdi:clipboard-check-outline';
const iconB = 'mdi:alert-outline';

const makeContent = (pack: Pack, locale: string): ToolLocaleContent<SolarBatteryAutonomyCalculatorUI> => {
  const [title1, para1, title2, para2, title3, para3, title4, para4] = pack.sections;
  const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: pack.faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
  const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: pack.title, description: pack.description, step: pack.howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };
  const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: pack.title, description: pack.description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: locale };
  return {
    slug: pack.slug, title: pack.title, description: pack.description, ui: pack.ui, faq: pack.faq, bibliography, howTo: pack.howTo, schemas: [faqSchema, howToSchema, appSchema],
    seo: [
      { type: 'title', text: title1, level: 2 },
      { type: 'paragraph', html: para1 },
      { type: 'stats', items: [{ value: 'W × h ÷ 1,000', label: pack.ui.loadWatts, icon: 'mdi:flash' }, { value: 'kWh × charge × efficiency', label: pack.ui.availableEnergy, icon: 'mdi:battery-check' }, { value: 'Available − planned', label: pack.ui.afterSchedule, icon: 'mdi:scale-balance' }], columns: 3 },
      { type: 'title', text: title2, level: 2 },
      { type: 'paragraph', html: para2 },
      { type: 'comparative', items: [{ ...pack.compare[0], icon: iconA }, { ...pack.compare[1], icon: iconB }], columns: 2 },
      { type: 'title', text: title3, level: 2 },
      { type: 'paragraph', html: para3 },
      { type: 'title', text: title4, level: 2 },
      { type: 'paragraph', html: para4 },
    ],
  };
};

const packs: Record<Exclude<string, 'en'>, Pack> = {
  de: {
    slug: 'solar-batterie-autonomie-rechner', title: 'Rechner für die Autonomie von Solarbatterien', description: 'Schätzen Sie die Laufzeit Ihrer Solarbatterie anhand nutzbarer Kapazität, Ladezustand, Wirkungsgrad und Haushaltsverbrauch.',
    ui: { setupEyebrow: 'IHR NACHTPLAN', setupTitle: 'Ein realistisches Zeitfenster erstellen', capacityLabel: 'Nutzbare Batteriekapazität', chargeLabel: 'Startladung', efficiencyLabel: 'Nutzbarer Wirkungsgrad', loadsTitle: 'Verbraucher, die laufen sollen', loadName: 'Name des Verbrauchers', loadWatts: 'Leistung', loadHours: 'Stunden', addLoad: 'Verbraucher hinzufügen', removeLoad: 'Entfernen', resultEyebrow: 'DAS ERGEBNIS', autonomyLabel: 'Geschätzte Autonomie', availableEnergy: 'Jetzt verfügbar', plannedDemand: 'Geplanter Bedarf', afterSchedule: 'Nach dem Zeitplan', coverage: 'Zeitplan-Abdeckung', shortfall: 'Es fehlen', enoughEnergy: 'Dieser Plan bleibt innerhalb der verfügbaren Batterieenergie.', biggestLoad: 'Größter Energieverbrauch', shiftSuggestion: 'Verschieben oder deaktivieren Sie diesen Verbraucher zuerst, wenn Sie mehr Reserve brauchen.', unitKwh: 'kWh', unitHours: 'h', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Fügen Sie mindestens einen Verbraucher hinzu, um die Schätzung zu sehen.' },
    faq: [{ question: 'Was bedeutet Batterieautonomie?', answer: 'Sie bezeichnet die geschätzte Zeit, in der die Batterie die gemeinsam eingetragenen Verbraucher versorgen kann. Die Schätzung nutzt nutzbare Kapazität, Startladung, Wirkungsgrad und Ihren Zeitplan.' }, { question: 'Berechnet das Tool die Solarproduktion am Tag?', answer: 'Nein. Es ist ein Szenario für Nacht- oder Notstrombetrieb und berücksichtigt weder Wetter noch Solarproduktion, Alterung, Wechselrichtergrenzen oder professionelle Auslegung.' }, { question: 'Warum wird der Wirkungsgrad berücksichtigt?', answer: 'Beim Weg durch Wechselrichter und Leitungen geht Energie verloren. Der Wirkungsgrad verhindert, dass nur mit der Nennkapazität gerechnet wird.' }, { question: 'Wie verlängere ich die Autonomie?', answer: 'Verschieben Sie flexible Verbraucher wie Waschmaschine, Warmwasser oder das Laden eines Fahrzeugs außerhalb des Batteriezeitfensters. Das Tool zeigt den größten Energieverbrauch zuerst.' }],
    howTo: [{ name: 'Nutzbare Kapazität eintragen', text: 'Verwenden Sie den nutzbaren Energiewert aus der Dokumentation Ihrer Batterie in Kilowattstunden.' }, { name: 'Startladung und Wirkungsgrad wählen', text: 'Legen Sie fest, wie viel Ladung zu Beginn vorhanden ist und welchen nutzbaren Wirkungsgrad Sie annehmen.' }, { name: 'Haushaltsverbrauch eintragen', text: 'Fügen Sie jedes Gerät mit seiner Leistung in Watt und der geplanten Laufzeit hinzu.' }, { name: 'Maßnahme aus dem Ergebnis ableiten', text: 'Nutzen Sie Autonomie und größten Verbraucher, um einen flexiblen Verbraucher zu verschieben oder auszuschalten.' }],
    sections: ['Wie lange reicht Ihre Solarbatterie über Nacht?', 'Die wichtige Frage lautet nicht nur, wie viele kWh die Batterie speichert, sondern wie viele Stunden sie Ihren tatsächlichen Nachtverbrauch abdeckt. Tragen Sie Kühlschrank, Router, Licht, Heizungssteuerung und Ladegeräte ein und erhalten Sie eine nachvollziehbare Schätzung der Notstrom-Laufzeit.', 'Was dieser Rechner für Batterie-Laufzeit zeigt', 'Das Hauptergebnis ist die geschätzte Autonomie in Stunden, berechnet aus der gemeinsamen Leistung Ihrer Verbraucher. Zusätzlich sehen Sie verfügbare Energie, Bedarf, Abdeckung und eine mögliche Lücke. Der größte Energieverbrauch weist auf die erste sinnvolle Verschiebung hin.', 'Den Zeitplan für den Notstrom verbessern', 'Beginnen Sie mit Verbrauchern, die viel Energie benötigen und zeitlich flexibel sind. Warmwasser, Waschen, Spülen oder Fahrzeugladen lassen sich oft aus dem Batteriezeitfenster verschieben. Ändern Sie eine Annahme nach der anderen und beobachten Sie die verbleibende Energie.', 'Die Grenzen der Schätzung kennen', 'Dies ist eine lokale Energiebilanz, keine professionelle Batterieauslegung. Wetter, Solarprognose, Alterung, Spitzenleistung und die Sicherheitsgrenzen Ihrer Anlage müssen anhand der Herstellerunterlagen geprüft werden.'],
    compare: [{ title: 'Ihre Nacht abbilden', description: 'Vergleichen Sie eine vollständige Abendroutine mit einem Plan für wichtige Verbraucher. Die Berechnung läuft im Browser und benötigt keinen Zugriff auf Ihre Anlage.', points: ['Nutzbare statt nomineller Kapazität verwenden', 'Laufzeit jedes Verbrauchers eintragen', 'Szenarien direkt vergleichen'] }, { title: 'Die Grenzen verstehen', description: 'Das Ergebnis ist ein transparentes Szenario und kein Nachweis für die Dimensionierung. Prüfen Sie Wechselrichter und Batterie immer mit der technischen Dokumentation.', points: ['Keine Wetter- oder Produktionsprognose', 'Kein Alterungsmodell', 'Keine Sicherheitsfreigabe'] }],
  },
  es: {
    slug: 'calculadora-autonomia-bateria-solar', title: 'Calculadora de autonomía de batería solar', description: 'Calcula cuánto dura una batería solar con tu capacidad útil, carga inicial, eficiencia y consumos domésticos.',
    ui: { setupEyebrow: 'TU PLAN NOCTURNO', setupTitle: 'Construye una ventana de batería realista', capacityLabel: 'Capacidad útil de la batería', chargeLabel: 'Carga inicial', efficiencyLabel: 'Eficiencia útil', loadsTitle: 'Consumos que seguirán activos', loadName: 'Nombre del consumo', loadWatts: 'Potencia', loadHours: 'Horas', addLoad: 'Añadir consumo', removeLoad: 'Eliminar', resultEyebrow: 'LA CONCLUSIÓN', autonomyLabel: 'Autonomía estimada', availableEnergy: 'Disponible ahora', plannedDemand: 'Demanda prevista', afterSchedule: 'Tras el horario', coverage: 'Cobertura del horario', shortfall: 'Te faltan', enoughEnergy: 'Este plan cabe dentro de la energía disponible de la batería.', biggestLoad: 'Mayor consumo energético', shiftSuggestion: 'Desplaza o apaga primero este consumo si necesitas más autonomía.', unitKwh: 'kWh', unitHours: 'h', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Añade al menos un consumo para ver la estimación.' },
    faq: [{ question: '¿Qué significa la autonomía de una batería?', answer: 'Es el tiempo estimado durante el que la batería puede alimentar la suma de los consumos de tu horario. Usa la capacidad útil, la carga inicial, la eficiencia y los equipos que introduces.' }, { question: '¿Calcula la producción solar durante el día?', answer: 'No. Es un escenario nocturno o de respaldo. No modela el tiempo, la generación solar, el envejecimiento, los límites del inversor ni el dimensionado profesional.' }, { question: '¿Por qué se incluye la eficiencia?', answer: 'La energía se pierde al pasar por el inversor y el cableado. Aplicar una eficiencia evita usar toda la capacidad nominal como si llegara intacta a tus equipos.' }, { question: '¿Cómo puedo aumentar la autonomía?', answer: 'Mueve fuera de la ventana de batería consumos flexibles como lavadora, agua caliente o carga del coche. El resultado destaca el consumo que más energía necesita.' }],
    howTo: [{ name: 'Introduce la capacidad útil', text: 'Usa la energía utilizable indicada en la documentación de tu batería, en kilovatios-hora.' }, { name: 'Indica carga y eficiencia', text: 'Elige la carga disponible al comenzar la noche y una estimación de la eficiencia útil del sistema.' }, { name: 'Añade los consumos', text: 'Introduce cada equipo, su potencia en vatios y las horas que estará funcionando.' }, { name: 'Toma una decisión', text: 'Usa la autonomía y el mayor consumo para decidir qué aparato desplazar o apagar.' }],
    sections: ['¿Cuánto durará tu batería solar durante la noche?', 'La pregunta útil no es solo cuántos kWh almacena tu batería, sino <strong>cuántas horas cubre tu noche real</strong>. Un frigorífico, el router, las luces, la calefacción y los cargadores consumen a ritmos distintos. Introduce los equipos que quieres mantener activos y obtén una estimación transparente de autonomía.', 'Qué te dice esta calculadora de autonomía', 'El resultado principal es la autonomía estimada en horas, calculada a partir de la potencia conjunta de tus consumos. También muestra la energía disponible, la demanda prevista, el porcentaje cubierto y el déficit. El mayor consumo te indica por dónde empezar a cambiar el horario.', 'Usa el resultado para mejorar tu respaldo', 'Empieza por los consumos que gastan mucho y son flexibles. El agua caliente, la lavadora, el lavavajillas o la carga del coche suelen poder salir de la ventana de batería. Cambia un dato cada vez y compara la energía que queda después del horario.', 'Conoce los límites del cálculo', 'Esto es un escenario de balance energético, no un dimensionado profesional. No predice producción solar, meteorología, degradación, picos de potencia ni los límites de seguridad de tu inversor o instalación.'],
    compare: [{ title: 'Modela tu noche', description: 'Compara una rutina completa con otra centrada en consumos esenciales. El cálculo se ejecuta en el navegador y no necesita conectarse a tu instalación.', points: ['Usa capacidad útil, no solo nominal', 'Indica las horas de cada equipo', 'Compara escenarios con rapidez'] }, { title: 'Interpreta sus límites', description: 'El resultado es una hipótesis transparente, no un certificado de diseño. Comprueba siempre la documentación de la batería y del inversor.', points: ['Sin previsión meteorológica', 'Sin modelo de envejecimiento', 'No sustituye consejo técnico'] }],
  },
  fr: {
    slug: 'calculateur-autonomie-batterie-solaire', title: "Calculateur d&apos;autonomie de batterie solaire", description: "Estimez la durée de secours d&apos;une batterie solaire selon sa capacité utile, sa charge, son rendement et vos appareils.",
    ui: { setupEyebrow: 'VOTRE PLAN DE NUIT', setupTitle: 'Construisez une plage réaliste', capacityLabel: 'Capacité utile de la batterie', chargeLabel: 'Charge initiale', efficiencyLabel: 'Rendement utile', loadsTitle: 'Appareils à maintenir', loadName: "Nom de l&apos;appareil", loadWatts: 'Puissance', loadHours: 'Heures', addLoad: 'Ajouter un appareil', removeLoad: 'Supprimer', resultEyebrow: 'À RETENIR', autonomyLabel: 'Autonomie estimée', availableEnergy: 'Disponible maintenant', plannedDemand: 'Demande prévue', afterSchedule: 'Après le programme', coverage: 'Couverture du programme', shortfall: 'Il manque', enoughEnergy: 'Ce programme tient dans l&apos;énergie disponible de la batterie.', biggestLoad: 'Plus forte dépense énergétique', shiftSuggestion: 'Décalez ou coupez d&apos;abord cet appareil si vous voulez plus de réserve.', unitKwh: 'kWh', unitHours: 'h', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Ajoutez au moins un appareil pour voir l&apos;estimation.' },
    faq: [{ question: "Que signifie l&apos;autonomie d&apos;une batterie ?", answer: "C&apos;est la durée estimée pendant laquelle la batterie alimente la puissance totale des appareils programmés. Le calcul utilise la capacité utile, la charge initiale, le rendement et vos appareils." }, { question: 'Le calcul inclut-il la production solaire du jour ?', answer: "Non. Il s&apos;agit d&apos;un scénario de nuit ou de secours. Il ne modélise ni la météo, ni la production, ni le vieillissement, ni les limites de l&apos;onduleur ou le dimensionnement professionnel." }, { question: 'Pourquoi intégrer le rendement ?', answer: "Une partie de l&apos;énergie est perdue dans l&apos;onduleur et les câbles. Le rendement évite de considérer que toute la capacité nominale arrive aux appareils." }, { question: 'Comment augmenter l&apos;autonomie ?', answer: 'Décalez le chauffe-eau, le lave-linge ou la recharge du véhicule hors de la plage de batterie. Le résultat signale la charge qui consomme le plus.' }],
    howTo: [{ name: 'Saisir la capacité utile', text: 'Utilisez la valeur d&apos;énergie utile indiquée par le fabricant, en kilowattheures.' }, { name: 'Régler charge et rendement', text: 'Indiquez la charge disponible au début de la période et le rendement utile estimé.' }, { name: 'Lister les appareils', text: 'Ajoutez chaque appareil avec sa puissance en watts et sa durée de fonctionnement.' }, { name: 'Agir sur le programme', text: 'Utilisez l&apos;autonomie et la plus grosse charge pour décider quel appareil décaler ou couper.' }],
    sections: ['Combien de temps votre batterie solaire tient-elle la nuit ?', 'La bonne question n&apos;est pas seulement combien de kWh votre batterie stocke, mais <strong>combien d&apos;heures elle couvre votre nuit réelle</strong>. Réfrigérateur, box internet, éclairage et chargeurs ne consomment pas au même rythme. Ajoutez vos appareils pour obtenir une estimation claire de l&apos;autonomie de secours.', 'Ce que mesure ce calculateur d&apos;autonomie', 'Le résultat principal est une durée en heures, calculée à partir de la puissance cumulée de vos appareils. Vous voyez aussi l&apos;énergie disponible, la demande du programme, son taux de couverture et le manque éventuel. La plus grosse dépense indique l&apos;action prioritaire.', 'Améliorez votre plan de secours', 'Commencez par les charges importantes mais flexibles. Eau chaude, lessive, lave-vaisselle et voiture peuvent souvent être planifiés hors de la plage de batterie. Modifiez une hypothèse à la fois et comparez l&apos;énergie restante.', 'Comprendre les limites', 'Il s&apos;agit d&apos;un scénario de bilan énergétique, pas d&apos;un dimensionnement professionnel. La météo, la production solaire, le vieillissement, les pointes de puissance et les limites de sécurité doivent être vérifiés dans la documentation de votre installation.'],
    compare: [{ title: 'Simuler votre nuit', description: 'Comparez une soirée complète avec un plan limité aux charges essentielles. Le calcul reste dans le navigateur et ne se connecte pas à votre installation.', points: ['Utiliser la capacité utile', 'Renseigner la durée réelle', 'Comparer plusieurs habitudes'] }, { title: 'Garder un cadre réaliste', description: 'Le résultat est un scénario explicable, pas une validation de conception. Consultez toujours les fiches de la batterie et de l&apos;onduleur.', points: ['Pas de prévision météo', 'Pas de vieillissement', 'Pas de conseil de sécurité'] }],
  },
  it: {
    slug: 'calcolatore-autonomia-batteria-solare', title: 'Calcolatore autonomia batteria solare', description: 'Stima per quante ore una batteria solare può alimentare i tuoi carichi, considerando carica iniziale ed efficienza.',
    ui: { setupEyebrow: 'IL TUO PIANO NOTTURNO', setupTitle: 'Crea una finestra realistica', capacityLabel: 'Capacità utile della batteria', chargeLabel: 'Carica iniziale', efficiencyLabel: 'Efficienza utile', loadsTitle: 'Carichi da mantenere attivi', loadName: 'Nome del carico', loadWatts: 'Potenza', loadHours: 'Ore', addLoad: 'Aggiungi carico', removeLoad: 'Rimuovi', resultEyebrow: 'IL RISULTATO', autonomyLabel: 'Autonomia stimata', availableEnergy: 'Disponibile ora', plannedDemand: 'Domanda prevista', afterSchedule: 'Dopo il programma', coverage: 'Copertura del programma', shortfall: 'Mancano', enoughEnergy: 'Questo piano rientra nell&apos;energia disponibile della batteria.', biggestLoad: 'Maggiore consumo energetico', shiftSuggestion: 'Sposta o spegni prima questo carico se ti serve più autonomia.', unitKwh: 'kWh', unitHours: 'h', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Aggiungi almeno un carico per vedere la stima.' },
    faq: [{ question: 'Cosa significa autonomia della batteria?', answer: 'È il tempo stimato in cui la batteria può alimentare la potenza complessiva dei carichi inseriti. Il calcolo usa capacità utile, carica iniziale, efficienza e programma.' }, { question: 'Calcola anche la produzione solare diurna?', answer: 'No. È uno scenario notturno o di backup e non modella meteo, produzione solare, invecchiamento, limiti dell&apos;inverter o dimensionamento professionale.' }, { question: 'Perché includere l&apos;efficienza?', answer: 'Una parte dell&apos;energia si perde nell&apos;inverter e nei cavi. L&apos;efficienza rende la stima più prudente rispetto alla sola capacità nominale.' }, { question: 'Come posso aumentare l&apos;autonomia?', answer: 'Sposta lavatrice, acqua calda o ricarica dell&apos;auto fuori dalla finestra della batteria. Il risultato evidenzia il carico che consuma più energia.' }],
    howTo: [{ name: 'Inserisci la capacità utile', text: 'Usa il valore di energia utilizzabile indicato nella documentazione della batteria, in kilowattora.' }, { name: 'Imposta carica ed efficienza', text: 'Scegli la carica presente all&apos;inizio della notte e l&apos;efficienza utile stimata del sistema.' }, { name: 'Elenca i carichi', text: 'Aggiungi ogni apparecchio con potenza in watt e ore di funzionamento.' }, { name: 'Applica il risultato', text: 'Usa autonomia e carico principale per decidere cosa spostare o spegnere.' }],
    sections: ['Quanto dura la batteria solare durante la notte?', 'La domanda utile non è solo quanti kWh contiene la batteria, ma <strong>quante ore copre la tua notte reale</strong>. Frigorifero, router, luci e caricabatterie consumano a ritmi diversi. Inserisci i carichi che vuoi mantenere e ottieni una stima trasparente del backup.', 'Cosa mostra questo calcolatore di autonomia', 'Il risultato principale è l&apos;autonomia in ore, calcolata dalla potenza complessiva dei carichi. Mostra anche energia disponibile, domanda prevista, percentuale coperta ed eventuale deficit. Il maggior consumo suggerisce da dove iniziare.', 'Migliora il tuo piano di backup', 'Parti dai carichi importanti ma flessibili. Acqua calda, lavatrice, lavastoviglie e ricarica dell&apos;auto spesso possono essere spostati. Modifica un dato alla volta e confronta l&apos;energia residua.', 'Conosci i limiti della stima', 'È uno scenario di bilancio energetico, non un dimensionamento professionale. Meteo, produzione, degrado, picchi di potenza e limiti di sicurezza vanno verificati nella documentazione dell&apos;impianto.'],
    compare: [{ title: 'Rappresenta la tua notte', description: 'Confronta una routine completa con un piano per i soli carichi essenziali. Il calcolo resta nel browser e non accede al tuo impianto.', points: ['Usa la capacità utile', 'Indica le ore di ogni apparecchio', 'Confronta scenari rapidamente'] }, { title: 'Leggi i limiti', description: 'Il risultato è uno scenario trasparente, non una certificazione. Controlla sempre batteria e inverter secondo le istruzioni del produttore.', points: ['Nessuna previsione meteo', 'Nessun modello di degrado', 'Nessun consiglio di sicurezza'] }],
  },
  pt: {
    slug: 'calculadora-autonomia-bateria-fotovoltaica', title: 'Calculadora de autonomia de bateria solar', description: 'Estime durante quanto tempo uma bateria solar alimenta os seus consumos, considerando carga inicial e eficiência.',
    ui: { setupEyebrow: 'O SEU PLANO NOTURNO', setupTitle: 'Crie uma janela de bateria realista', capacityLabel: 'Capacidade útil da bateria', chargeLabel: 'Carga inicial', efficiencyLabel: 'Eficiência útil', loadsTitle: 'Consumos a manter ligados', loadName: 'Nome do consumo', loadWatts: 'Potência', loadHours: 'Horas', addLoad: 'Adicionar consumo', removeLoad: 'Remover', resultEyebrow: 'A CONCLUSÃO', autonomyLabel: 'Autonomia estimada', availableEnergy: 'Disponível agora', plannedDemand: 'Consumo previsto', afterSchedule: 'Após o horário', coverage: 'Cobertura do horário', shortfall: 'Faltam', enoughEnergy: 'Este plano cabe na energia disponível da bateria.', biggestLoad: 'Maior consumo de energia', shiftSuggestion: 'Adie ou desligue primeiro este consumo se precisar de mais autonomia.', unitKwh: 'kWh', unitHours: 'h', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Adicione pelo menos um consumo para ver a estimativa.' },
    faq: [{ question: 'O que significa autonomia da bateria?', answer: 'É o tempo estimado durante o qual a bateria consegue alimentar a potência combinada dos consumos no seu plano. Usa capacidade útil, carga inicial, eficiência e os consumos indicados.' }, { question: 'Calcula a produção solar durante o dia?', answer: 'Não. É um cenário noturno ou de backup e não modela meteorologia, produção solar, envelhecimento, limites do inversor ou dimensionamento profissional.' }, { question: 'Por que é incluída a eficiência?', answer: 'Perde-se energia no inversor e na cablagem. A eficiência evita assumir que toda a capacidade nominal chega aos aparelhos.' }, { question: 'Como aumentar a autonomia?', answer: 'Passe máquina de lavar, água quente ou carregamento do carro para fora da janela da bateria. O resultado mostra o consumo que exige mais energia.' }],
    howTo: [{ name: 'Introduza a capacidade útil', text: 'Use o valor de energia utilizável indicado na documentação da bateria, em quilowatt-hora.' }, { name: 'Defina carga e eficiência', text: 'Escolha a carga disponível no início da noite e uma estimativa da eficiência útil do sistema.' }, { name: 'Liste os consumos', text: 'Adicione cada aparelho, a potência em watts e o número de horas de funcionamento.' }, { name: 'Aja sobre o resultado', text: 'Use a autonomia e o maior consumo para decidir que aparelho adiar ou desligar.' }],
    sections: ['Quanto tempo dura a sua bateria solar durante a noite?', 'A pergunta importante não é apenas quantos kWh a bateria armazena, mas <strong>quantas horas cobre a sua noite real</strong>. Frigorífico, router, luzes e carregadores consomem de forma diferente. Introduza os consumos que pretende manter e obtenha uma estimativa clara de autonomia.', 'O que mostra esta calculadora de autonomia', 'O resultado principal é a autonomia em horas, calculada a partir da potência total dos consumos. Também apresenta energia disponível, procura prevista, percentagem coberta e eventual défice. O maior consumo indica a primeira alteração a considerar.', 'Melhore o seu plano de backup', 'Comece pelos consumos flexíveis que usam mais energia. Água quente, máquinas, loiça e carregamento do veículo podem muitas vezes ser adiados. Altere uma hipótese de cada vez e compare a energia que sobra.', 'Conheça os limites', 'Este é um cenário de balanço energético, não um dimensionamento profissional. Meteorologia, produção, degradação, picos de potência e limites de segurança devem ser confirmados na documentação do sistema.'],
    compare: [{ title: 'Modele a sua noite', description: 'Compare uma rotina completa com um plano apenas para consumos essenciais. O cálculo funciona no navegador e não acede à sua instalação.', points: ['Use capacidade útil', 'Indique as horas de cada aparelho', 'Compare cenários rapidamente'] }, { title: 'Mantenha o contexto', description: 'O resultado é um cenário explicável, não uma validação de projeto. Consulte sempre a documentação da bateria e do inversor.', points: ['Sem previsão meteorológica', 'Sem modelo de envelhecimento', 'Sem aconselhamento de segurança'] }],
  },
  nl: {
    slug: 'zonnebatterij-autonomie-calculator', title: 'Calculator voor autonomie van een thuisbatterij', description: 'Schat hoe lang uw thuisbatterij uw verbruik kan voeden op basis van bruikbare capaciteit, lading en rendement.',
    ui: { setupEyebrow: 'UW NACHTPLAN', setupTitle: 'Bouw een realistisch batterijvenster', capacityLabel: 'Bruikbare batterijcapaciteit', chargeLabel: 'Startlading', efficiencyLabel: 'Bruikbaar rendement', loadsTitle: 'Verbruikers die aanblijven', loadName: 'Naam verbruiker', loadWatts: 'Vermogen', loadHours: 'Uren', addLoad: 'Verbruiker toevoegen', removeLoad: 'Verwijderen', resultEyebrow: 'DE UITKOMST', autonomyLabel: 'Geschatte autonomie', availableEnergy: 'Nu beschikbaar', plannedDemand: 'Gepland verbruik', afterSchedule: 'Na het schema', coverage: 'Dekking van schema', shortfall: 'Tekort', enoughEnergy: 'Dit plan past binnen de beschikbare batterij-energie.', biggestLoad: 'Grootste energieverbruik', shiftSuggestion: 'Verschuif of schakel deze verbruiker eerst uit voor meer reserve.', unitKwh: 'kWh', unitHours: 'u', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Voeg minstens één verbruiker toe voor een schatting.' },
    faq: [{ question: 'Wat betekent batterijautonomie?', answer: 'Het is de geschatte tijd waarin de batterij het gecombineerde vermogen van uw geplande verbruikers kan leveren. De berekening gebruikt bruikbare capaciteit, startlading, rendement en uw schema.' }, { question: 'Berekent dit ook zonneproductie overdag?', answer: 'Nee. Dit is een scenario voor de nacht of noodstroom. Weer, zonneproductie, veroudering, omvormerlimieten en professionele dimensionering vallen buiten de berekening.' }, { question: 'Waarom telt rendement mee?', answer: 'In de omvormer en bekabeling gaat energie verloren. Met rendement krijgt u een voorzichtiger schatting dan met alleen de nominale capaciteit.' }, { question: 'Hoe verleng ik de autonomie?', answer: 'Plan wassen, warm water of laden van een auto buiten het batterijvenster. De uitkomst toont welke verbruiker het meeste energie vraagt.' }],
    howTo: [{ name: 'Vul bruikbare capaciteit in', text: 'Gebruik de bruikbare energie uit de batterijdocumentatie, uitgedrukt in kilowattuur.' }, { name: 'Stel lading en rendement in', text: 'Kies de lading bij het begin van de periode en het geschatte bruikbare rendement.' }, { name: 'Voeg verbruikers toe', text: 'Vermeld elk apparaat met zijn vermogen in watt en het aantal bedrijfsuren.' }, { name: 'Gebruik de uitkomst', text: 'Gebruik autonomie en grootste verbruiker om te beslissen wat u verplaatst of uitschakelt.' }],
    sections: ['Hoe lang houdt uw thuisbatterij in de nacht vol?', 'De vraag is niet alleen hoeveel kWh uw batterij opslaat, maar <strong>hoeveel uur ze uw echte nacht dekt</strong>. Koelkast, router, verlichting en laders gebruiken energie in verschillende tempo&apos;s. Voeg uw verbruikers toe voor een heldere schatting van de back-upruntime.', 'Wat deze autonomiecalculator laat zien', 'De hoofduitkomst is autonomie in uren op basis van het gezamenlijke vermogen. U ziet ook beschikbare energie, gepland verbruik, dekking en een eventueel tekort. De grootste energieverbruiker geeft aan waar u het eerst kunt bijsturen.', 'Maak uw back-upplan beter', 'Begin met verbruikers die veel energie vragen maar flexibel zijn. Warm water, was, vaat en autoladen kunnen vaak buiten het batterijvenster. Wijzig telkens één aanname en vergelijk de resterende energie.', 'Ken de grenzen van de schatting', 'Dit is een energiebalansscenario, geen professionele dimensionering. Controleer weer, productie, degradatie, piekvermogen en veiligheidslimieten in de documentatie van uw installatie.'],
    compare: [{ title: 'Uw nacht modelleren', description: 'Vergelijk een volledige avondroutine met een plan voor essentiele verbruikers. De berekening gebeurt in de browser zonder toegang tot uw installatie.', points: ['Gebruik bruikbare capaciteit', 'Vul de looptijd per apparaat in', 'Vergelijk scenario&apos;s direct'] }, { title: 'De beperking begrijpen', description: 'De uitkomst is een transparant scenario, geen ontwerpgoedkeuring. Raadpleeg altijd de gegevens van batterij en omvormer.', points: ['Geen weersvoorspelling', 'Geen verouderingsmodel', 'Geen veiligheidsadvies'] }],
  },
  sv: {
    slug: 'solbatteri-autonomikalkylator', title: 'Kalkylator för solbatteriets drifttid', description: 'Uppskatta hur länge ett solbatteri kan driva dina laster utifrån användbar kapacitet, laddning och verkningsgrad.',
    ui: { setupEyebrow: 'DIN NATTPLAN', setupTitle: 'Bygg ett realistiskt batterifönster', capacityLabel: 'Användbar batterikapacitet', chargeLabel: 'Startladdning', efficiencyLabel: 'Användbar verkningsgrad', loadsTitle: 'Laster som ska vara på', loadName: 'Lastens namn', loadWatts: 'Effekt', loadHours: 'Timmar', addLoad: 'Lägg till last', removeLoad: 'Ta bort', resultEyebrow: 'SLUTSATSEN', autonomyLabel: 'Beräknad drifttid', availableEnergy: 'Tillgängligt nu', plannedDemand: 'Planerad energi', afterSchedule: 'Efter schemat', coverage: 'Täckning av schemat', shortfall: 'Du saknar', enoughEnergy: 'Planen ryms inom batteriets tillgängliga energi.', biggestLoad: 'Största energiförbrukning', shiftSuggestion: 'Flytta eller stäng av denna last först om du behöver mer reserv.', unitKwh: 'kWh', unitHours: 'h', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Lägg till minst en last för att se uppskattningen.' },
    faq: [{ question: 'Vad betyder batteriets drifttid?', answer: 'Det är den uppskattade tid som batteriet kan leverera den sammanlagda effekten från dina planerade laster. Beräkningen använder användbar kapacitet, startladdning, verkningsgrad och schema.' }, { question: 'Beräknar den solproduktionen dagtid?', answer: 'Nej. Det är ett scenario för natt eller reservkraft. Väder, solproduktion, åldrande, växelriktargränser och professionell dimensionering ingår inte.' }, { question: 'Varför ingår verkningsgrad?', answer: 'Energi förloras i växelriktare och kablage. Verkningsgraden ger en mer försiktig uppskattning än att använda hela märkeffekten.' }, { question: 'Hur förlänger jag drifttiden?', answer: 'Flytta tvätt, varmvatten eller billaddning utanför batterifönstret. Resultatet visar vilken last som använder mest energi.' }],
    howTo: [{ name: 'Ange användbar kapacitet', text: 'Använd den användbara energimängd som anges i batteriets dokumentation, i kilowattimmar.' }, { name: 'Ställ laddning och verkningsgrad', text: 'Välj laddningen när perioden börjar och systemets uppskattade användbara verkningsgrad.' }, { name: 'Lista dina laster', text: 'Lägg till varje apparat med effekt i watt och antal drifttimmar.' }, { name: 'Agera på resultatet', text: 'Använd drifttiden och största last för att välja vad som ska flyttas eller stängas av.' }],
    sections: ['Hur länge räcker solbatteriet under natten?', 'Den viktiga frågan är inte bara hur många kWh batteriet lagrar, utan <strong>hur många timmar det täcker din verkliga natt</strong>. Kyl, router, belysning och laddare använder energi i olika takt. Lägg in lasterna för en tydlig uppskattning av reservtiden.', 'Det här visar kalkylatorn', 'Huvudresultatet är drifttid i timmar utifrån den sammanlagda effekten. Du ser också tillgänglig energi, planerad efterfrågan, täckning och eventuellt underskott. Den största förbrukningen visar var du kan börja ändra schemat.', 'Förbättra din reservplan', 'Börja med laster som använder mycket energi men är flexibla. Varmvatten, tvätt, disk och billaddning kan ofta flyttas. Ändra en uppgift i taget och jämför energin som finns kvar.', 'Känn till begränsningarna', 'Detta är ett energibalansscenario, inte professionell dimensionering. Kontrollera väder, produktion, degradering, toppeffekt och säkerhetsgränser i anläggningens dokumentation.'],
    compare: [{ title: 'Modellera din natt', description: 'Jämför en komplett kväll med en plan för viktiga laster. Beräkningen körs i webbläsaren utan åtkomst till din installation.', points: ['Använd användbar kapacitet', 'Ange varje lasts timmar', 'Jämför scenarier direkt'] }, { title: 'Förstå ramen', description: 'Resultatet är ett transparent scenario, inte ett konstruktionsbesked. Läs alltid batteriets och växelriktarens uppgifter.', points: ['Ingen väderprognos', 'Ingen åldringsmodell', 'Inga säkerhetsråd'] }],
  },
  pl: {
    slug: 'kalkulator-autonomii-baterii-solarnej', title: 'Kalkulator autonomii baterii solarnej', description: 'Oszacuj, jak długo bateria solarna zasili domowe odbiorniki na podstawie pojemności użytkowej, naładowania i sprawności.',
    ui: { setupEyebrow: 'TWÓJ PLAN NA NOC', setupTitle: 'Zbuduj realistyczne okno pracy baterii', capacityLabel: 'Użyteczna pojemność baterii', chargeLabel: 'Początkowy poziom naładowania', efficiencyLabel: 'Użyteczna sprawność', loadsTitle: 'Odbiorniki, które mają działać', loadName: 'Nazwa odbiornika', loadWatts: 'Moc', loadHours: 'Godziny', addLoad: 'Dodaj odbiornik', removeLoad: 'Usuń', resultEyebrow: 'NAJWAŻNIEJSZE', autonomyLabel: 'Szacowana autonomia', availableEnergy: 'Dostępna energia', plannedDemand: 'Planowane zużycie', afterSchedule: 'Po harmonogramie', coverage: 'Pokrycie harmonogramu', shortfall: 'Brakuje', enoughEnergy: 'Ten plan mieści się w dostępnej energii baterii.', biggestLoad: 'Największy pobór energii', shiftSuggestion: 'Przenieś lub wyłącz ten odbiornik jako pierwszy, jeśli potrzebujesz większego zapasu.', unitKwh: 'kWh', unitHours: 'h', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Dodaj co najmniej jeden odbiornik, aby zobaczyć wynik.' },
    faq: [{ question: 'Co oznacza autonomia baterii?', answer: 'To szacowany czas, przez który bateria może zasilać łączną moc odbiorników w harmonogramie. Obliczenie uwzględnia pojemność użytkową, początkowe naładowanie, sprawność i wpisane odbiorniki.' }, { question: 'Czy kalkulator oblicza dzienną produkcję energii?', answer: 'Nie. To scenariusz nocny lub awaryjny. Nie uwzględnia pogody, produkcji solarnej, starzenia baterii, ograniczeń falownika ani profesjonalnego doboru instalacji.' }, { question: 'Dlaczego uwzględniana jest sprawność?', answer: 'Część energii tracona jest w falowniku i przewodach. Sprawność daje ostrożniejszy wynik niż użycie samej pojemności znamionowej.' }, { question: 'Jak wydłużyć autonomię?', answer: 'Przenieś pranie, podgrzewanie wody lub ładowanie samochodu poza okno pracy baterii. Wynik pokazuje odbiornik o największym zużyciu.' }],
    howTo: [{ name: 'Wpisz pojemność użytkową', text: 'Użyj wartości energii użytkowej z dokumentacji baterii, podanej w kilowatogodzinach.' }, { name: 'Ustaw naładowanie i sprawność', text: 'Wybierz poziom naładowania na początku okresu oraz szacowaną sprawność systemu.' }, { name: 'Dodaj odbiorniki', text: 'Podaj każde urządzenie, jego moc w watach i liczbę godzin pracy.' }, { name: 'Wykorzystaj wynik', text: 'Na podstawie autonomii i największego odbiornika zdecyduj, co przesunąć lub wyłączyć.' }],
    sections: ['Jak długo bateria solarna działa w nocy?', 'Najważniejsze pytanie nie brzmi tylko, ile kWh przechowuje bateria, lecz <strong>ile godzin pokrywa Twoją rzeczywistą noc</strong>. Lodówka, router, oświetlenie i ładowarki mają różne profile zużycia. Wpisz odbiorniki, aby otrzymać przejrzyste oszacowanie czasu podtrzymania.', 'Co pokazuje kalkulator autonomii baterii', 'Główny wynik to autonomia w godzinach obliczona z łącznej mocy odbiorników. Zobaczysz także dostępną energię, planowane zużycie, procent pokrycia i ewentualny niedobór. Największy pobór wskazuje pierwszą zmianę harmonogramu.', 'Ulepsz plan zasilania awaryjnego', 'Zacznij od odbiorników, które zużywają dużo energii, ale mogą działać o innej porze. Ciepła woda, pranie, zmywanie i ładowanie auta często da się przesunąć. Zmieniaj jedno założenie naraz.', 'Poznaj ograniczenia wyniku', 'To scenariusz bilansu energii, a nie profesjonalny dobór baterii. Pogodę, produkcję, degradację, moc szczytową i limity bezpieczeństwa sprawdź w dokumentacji instalacji.'],
    compare: [{ title: 'Odwzoruj swoją noc', description: 'Porównaj pełną rutynę wieczorną z planem obejmującym tylko najważniejsze odbiorniki. Obliczenia działają w przeglądarce.', points: ['Użyj pojemności użytkowej', 'Podaj czas pracy urządzeń', 'Porównaj kilka scenariuszy'] }, { title: 'Zachowaj ostrożność', description: 'Wynik to przejrzysty scenariusz, nie zatwierdzenie projektu. Zawsze sprawdzaj dane baterii i falownika.', points: ['Bez prognozy pogody', 'Bez modelu starzenia', 'Bez porad bezpieczeństwa'] }],
  },
  id: {
    slug: 'kalkulator-kemandirian-baterai-surya', title: 'Kalkulator Kemandirian Baterai Surya', description: 'Perkirakan berapa lama baterai surya rumah dapat menyalakan beban berdasarkan kapasitas yang dapat digunakan, daya awal, dan efisiensi.',
    ui: { setupEyebrow: 'RENCANA MALAM ANDA', setupTitle: 'Buat rentang baterai yang realistis', capacityLabel: 'Kapasitas baterai yang dapat digunakan', chargeLabel: 'Daya awal', efficiencyLabel: 'Efisiensi yang dapat digunakan', loadsTitle: 'Beban yang tetap menyala', loadName: 'Nama beban', loadWatts: 'Daya', loadHours: 'Jam', addLoad: 'Tambah beban', removeLoad: 'Hapus', resultEyebrow: 'KESIMPULAN', autonomyLabel: 'Perkiraan waktu pakai', availableEnergy: 'Tersedia sekarang', plannedDemand: 'Kebutuhan terencana', afterSchedule: 'Setelah jadwal', coverage: 'Cakupan jadwal', shortfall: 'Kekurangan', enoughEnergy: 'Rencana ini masih sesuai dengan energi baterai yang tersedia.', biggestLoad: 'Pemakaian energi terbesar', shiftSuggestion: 'Pindahkan atau matikan beban ini terlebih dahulu jika membutuhkan cadangan lebih lama.', unitKwh: 'kWh', unitHours: 'jam', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Tambahkan setidaknya satu beban untuk melihat perkiraan.' },
    faq: [{ question: 'Apa arti kemandirian baterai?', answer: 'Ini adalah perkiraan waktu baterai dapat memasok daya gabungan dari beban dalam jadwal Anda. Perhitungan memakai kapasitas yang dapat digunakan, daya awal, efisiensi, dan beban yang dimasukkan.' }, { question: 'Apakah produksi surya siang hari ikut dihitung?', answer: 'Tidak. Ini adalah skenario malam atau cadangan. Cuaca, produksi surya, penuaan baterai, batas inverter, dan ukuran profesional tidak dimodelkan.' }, { question: 'Mengapa efisiensi ikut dihitung?', answer: 'Energi hilang melalui inverter dan kabel. Efisiensi membuat perkiraan lebih konservatif daripada memakai kapasitas nominal saja.' }, { question: 'Bagaimana memperpanjang waktu pakai?', answer: 'Pindahkan mesin cuci, pemanas air, atau pengisian kendaraan di luar waktu baterai. Hasilnya menyoroti beban yang paling banyak memakai energi.' }],
    howTo: [{ name: 'Masukkan kapasitas yang dapat digunakan', text: 'Gunakan nilai energi yang dapat digunakan dari dokumentasi baterai dalam kilowatt-jam.' }, { name: 'Atur daya awal dan efisiensi', text: 'Pilih daya yang tersedia saat periode dimulai dan perkiraan efisiensi sistem.' }, { name: 'Daftarkan beban rumah', text: 'Tambahkan setiap perangkat, dayanya dalam watt, dan lama pemakaiannya.' }, { name: 'Gunakan hasilnya', text: 'Gunakan waktu pakai dan beban terbesar untuk menentukan perangkat yang dipindahkan atau dimatikan.' }],
    sections: ['Berapa lama baterai surya bertahan semalaman?', 'Pertanyaan yang berguna bukan hanya berapa kWh yang disimpan baterai, tetapi <strong>berapa jam baterai menutup kebutuhan malam Anda</strong>. Kulkas, router, lampu, dan pengisi daya memakai energi dengan laju berbeda. Masukkan beban untuk mendapat perkiraan cadangan yang mudah dipahami.', 'Yang ditunjukkan kalkulator ini', 'Hasil utama adalah perkiraan waktu pakai dalam jam berdasarkan daya gabungan beban. Anda juga melihat energi tersedia, kebutuhan terencana, persentase cakupan, dan kekurangan. Beban terbesar menunjukkan tindakan pertama yang paling masuk akal.', 'Perbaiki rencana cadangan Anda', 'Mulai dari beban yang besar tetapi fleksibel. Pemanas air, mesin cuci, mesin pencuci piring, dan pengisian kendaraan sering dapat dijadwalkan ulang. Ubah satu asumsi setiap kali dan bandingkan energi tersisa.', 'Pahami batas perkiraan', 'Ini adalah skenario keseimbangan energi, bukan penentuan ukuran instalasi profesional. Periksa cuaca, produksi, degradasi, daya puncak, dan batas keselamatan pada dokumentasi sistem.'],
    compare: [{ title: 'Modelkan malam Anda', description: 'Bandingkan rutinitas malam lengkap dengan rencana untuk beban penting saja. Perhitungan berjalan di browser tanpa mengakses instalasi.', points: ['Gunakan kapasitas yang dapat dipakai', 'Masukkan jam tiap perangkat', 'Bandingkan beberapa skenario'] }, { title: 'Ketahui batasnya', description: 'Hasil ini adalah skenario transparan, bukan sertifikasi desain. Selalu periksa dokumentasi baterai dan inverter.', points: ['Tanpa prakiraan cuaca', 'Tanpa model penuaan', 'Tanpa panduan keselamatan'] }],
  },
  tr: {
    slug: 'gunes-bataryasi-otonomi-hesaplayici', title: 'Güneş Enerjisi Batarya Özerklik Hesaplayıcı', description: 'Kullanılabilir kapasite, başlangıç şarjı ve verimliliği kullanarak ev bataryasının yükleri ne kadar süre besleyeceğini tahmin edin.',
    ui: { setupEyebrow: 'GECE PLANINIZ', setupTitle: 'Gerçekçi bir batarya aralığı oluşturun', capacityLabel: 'Kullanılabilir batarya kapasitesi', chargeLabel: 'Başlangıç şarjı', efficiencyLabel: 'Kullanılabilir verimlilik', loadsTitle: 'Çalışmaya devam edecek yükler', loadName: 'Yük adı', loadWatts: 'Güç', loadHours: 'Saat', addLoad: 'Yük ekle', removeLoad: 'Kaldır', resultEyebrow: 'SONUÇ', autonomyLabel: 'Tahmini özerklik', availableEnergy: 'Şimdi kullanılabilir', plannedDemand: 'Planlanan tüketim', afterSchedule: 'Programdan sonra', coverage: 'Program kapsamı', shortfall: 'Eksik enerji', enoughEnergy: 'Bu plan kullanılabilir batarya enerjisi içinde kalıyor.', biggestLoad: 'En büyük enerji tüketimi', shiftSuggestion: 'Daha uzun yedek süreye ihtiyacınız varsa önce bu yükü erteleyin veya kapatın.', unitKwh: 'kWh', unitHours: 's', unitWatts: 'W', unitPercent: '%', emptyLoads: 'Tahmini görmek için en az bir yük ekleyin.' },
    faq: [{ question: 'Batarya özerkliği ne demektir?', answer: 'Bataryanın programınızdaki yüklerin toplam gücünü sağlayabileceği tahmini süredir. Hesaplama kullanılabilir kapasiteyi, başlangıç şarjını, verimliliği ve girdiğiniz yükleri kullanır.' }, { question: 'Gündüz güneş üretimini hesaplar mı?', answer: 'Hayır. Bu bir gece veya yedekleme senaryosudur. Hava durumunu, güneş üretimini, yaşlanmayı, inverter sınırlarını veya profesyonel boyutlandırmayı modellemez.' }, { question: 'Verimlilik neden hesaba katılır?', answer: 'Inverter ve kablolarda enerji kaybolur. Verimlilik, yalnızca nominal kapasiteyi kullanmaktan daha temkinli bir sonuç verir.' }, { question: 'Özerkliği nasıl artırabilirim?', answer: 'Çamaşır, sıcak su veya araç şarjını batarya aralığının dışına taşıyın. Sonuç, en çok enerji kullanan yükü gösterir.' }],
    howTo: [{ name: 'Kullanılabilir kapasiteyi girin', text: 'Batarya belgelerindeki kullanılabilir enerji değerini kilovat-saat olarak kullanın.' }, { name: 'Şarjı ve verimliliği ayarlayın', text: 'Dönem başındaki şarjı ve sistemin yaklaşık kullanılabilir verimliliğini seçin.' }, { name: 'Yükleri listeleyin', text: 'Her cihazı gücü ve çalışacağı saat sayısıyla ekleyin.' }, { name: 'Sonuca göre karar verin', text: 'Özerkliği ve en büyük yükü kullanarak hangi cihazı erteleyeceğinize karar verin.' }],
    sections: ['Güneş bataryanız gece ne kadar dayanır?', 'Asıl soru bataryanın kaç kWh depoladığı değil, <strong>gerçek gece tüketiminizi kaç saat karşılayabildiğidir</strong>. Buzdolabı, modem, aydınlatma ve şarj cihazları farklı hızlarda enerji harcar. Yükleri girerek anlaşılır bir yedekleme süresi tahmini alın.', 'Bu batarya süresi hesaplayıcısı ne gösterir?', 'Ana sonuç, yüklerin toplam gücünden hesaplanan saat cinsinden özerkliktir. Kullanılabilir enerjiyi, planlanan tüketimi, kapsama oranını ve açığı da görürsünüz. En büyük tüketim, ilk değişikliği nerede yapacağınızı gösterir.', 'Yedekleme planınızı iyileştirin', 'Çok enerji tüketen ancak esnek yüklerle başlayın. Sıcak su, çamaşır, bulaşık ve araç şarjı çoğu zaman ertelenebilir. Her seferinde tek bir varsayımı değiştirerek kalan enerjiyi karşılaştırın.', 'Tahminin sınırlarını bilin', 'Bu bir enerji dengesi senaryosudur, profesyonel sistem boyutlandırması değildir. Hava, üretim, yıpranma, tepe güç ve güvenlik sınırlarını sistem belgelerinden kontrol edin.'],
    compare: [{ title: 'Gecenizi modelleyin', description: 'Tam bir akşam rutiniyle yalnızca gerekli yüklerden oluşan planı karşılaştırın. Hesaplama tarayıcıda çalışır ve tesisata erişmez.', points: ['Kullanılabilir kapasiteyi kullanın', 'Her yükün saatini girin', 'Senaryoları karşılaştırın'] }, { title: 'Çerçeveyi koruyun', description: 'Sonuç şeffaf bir senaryodur, tasarım onayı değildir. Batarya ve inverter belgelerini her zaman kontrol edin.', points: ['Hava tahmini yoktur', 'Yaşlanma modeli yoktur', 'Güvenlik tavsiyesi değildir'] }],
  },
  ru: {
    slug: 'kalkulyator-avtonomii-solnechnoy-batarei', title: 'Калькулятор автономности солнечной батареи', description: 'Оцените, как долго домашняя батарея сможет питать нагрузки с учетом доступной емкости, заряда и эффективности.',
    ui: { setupEyebrow: 'НОЧНОЙ ПЛАН', setupTitle: 'Составьте реалистичный сценарий', capacityLabel: 'Доступная емкость батареи', chargeLabel: 'Начальный заряд', efficiencyLabel: 'Рабочий КПД', loadsTitle: 'Нагрузки, которые останутся включенными', loadName: 'Название нагрузки', loadWatts: 'Мощность', loadHours: 'Часы', addLoad: 'Добавить нагрузку', removeLoad: 'Удалить', resultEyebrow: 'ИТОГ', autonomyLabel: 'Расчетная автономность', availableEnergy: 'Доступно сейчас', plannedDemand: 'Планируемый расход', afterSchedule: 'После сценария', coverage: 'Покрытие сценария', shortfall: 'Не хватает', enoughEnergy: 'Этот план укладывается в доступную энергию батареи.', biggestLoad: 'Самый большой расход', shiftSuggestion: 'Если нужен больший запас, сначала перенесите или отключите эту нагрузку.', unitKwh: 'кВт·ч', unitHours: 'ч', unitWatts: 'Вт', unitPercent: '%', emptyLoads: 'Добавьте хотя бы одну нагрузку, чтобы увидеть оценку.' },
    faq: [{ question: 'Что означает автономность батареи?', answer: 'Это расчетное время, в течение которого батарея может питать суммарную мощность нагрузок из вашего сценария. Учитываются доступная емкость, начальный заряд, КПД и введенные нагрузки.' }, { question: 'Учитывает ли калькулятор дневную выработку солнца?', answer: 'Нет. Это сценарий для ночи или резервного питания. Погода, солнечная генерация, старение батареи, ограничения инвертора и профессиональный подбор не моделируются.' }, { question: 'Зачем учитывать КПД?', answer: 'Часть энергии теряется в инверторе и проводах. КПД делает оценку осторожнее, чем расчет только по номинальной емкости.' }, { question: 'Как увеличить автономность?', answer: 'Перенесите стирку, нагрев воды или зарядку автомобиля за пределы периода работы батареи. Результат покажет нагрузку с наибольшим расходом.' }],
    howTo: [{ name: 'Введите доступную емкость', text: 'Возьмите значение доступной энергии из документации батареи в киловатт-часах.' }, { name: 'Задайте заряд и КПД', text: 'Укажите заряд в начале периода и примерный рабочий КПД системы.' }, { name: 'Добавьте нагрузки', text: 'Введите каждый прибор, его мощность в ваттах и часы работы.' }, { name: 'Примите решение', text: 'Используйте автономность и крупнейшую нагрузку, чтобы выбрать, что перенести или отключить.' }],
    sections: ['На сколько часов хватит солнечной батареи ночью?', 'Важен не только вопрос, сколько кВт·ч хранит батарея, а <strong>сколько часов она покрывает вашу настоящую ночь</strong>. Холодильник, роутер, освещение и зарядные устройства расходуют энергию по-разному. Добавьте нагрузки и получите понятную оценку резервного времени.', 'Что показывает калькулятор автономности', 'Главный результат - автономность в часах на основе общей мощности нагрузок. Дополнительно отображаются доступная энергия, планируемый расход, покрытие и возможный дефицит. Самый большой расход подсказывает первое изменение сценария.', 'Улучшите план резервного питания', 'Начните с крупных, но гибких нагрузок. Нагрев воды, стирку, посудомоечную машину и зарядку автомобиля часто можно перенести. Меняйте по одному параметру и сравнивайте остаток энергии.', 'Понимайте границы оценки', 'Это сценарий энергетического баланса, а не профессиональный расчет системы. Проверьте погоду, генерацию, деградацию, пиковую мощность и ограничения безопасности по документации.'],
    compare: [{ title: 'Смоделируйте свою ночь', description: 'Сравните полный вечерний сценарий с планом только для важных нагрузок. Расчет выполняется в браузере без доступа к установке.', points: ['Используйте доступную емкость', 'Укажите часы работы приборов', 'Сравните сценарии'] }, { title: 'Не выходите за рамки', description: 'Результат - прозрачный сценарий, а не разрешение на проектирование. Всегда сверяйтесь с данными батареи и инвертора.', points: ['Без прогноза погоды', 'Без модели старения', 'Без рекомендаций по безопасности'] }],
  },
  ja: {
    slug: 'solar-battery-autonomy-calculator', title: '太陽光蓄電池の自給時間計算機', description: '使用可能容量、開始時の充電率、効率、家庭の負荷から、太陽光蓄電池のバックアップ時間を見積もります。',
    ui: { setupEyebrow: '夜間の計画', setupTitle: '現実的な蓄電池の使用時間を作る', capacityLabel: '使用可能な蓄電池容量', chargeLabel: '開始時の充電率', efficiencyLabel: '使用可能な効率', loadsTitle: '稼働させる負荷', loadName: '負荷名', loadWatts: '電力', loadHours: '時間', addLoad: '負荷を追加', removeLoad: '削除', resultEyebrow: '計算結果', autonomyLabel: '推定自給時間', availableEnergy: '現在使えるエネルギー', plannedDemand: '予定消費量', afterSchedule: '予定後の残量', coverage: '予定のカバー率', shortfall: '不足量', enoughEnergy: 'この計画は使用可能な蓄電池エネルギー内に収まります。', biggestLoad: '最大のエネルギー消費', shiftSuggestion: '予備時間を延ばしたい場合は、まずこの負荷を移動または停止してください。', unitKwh: 'kWh', unitHours: '時間', unitWatts: 'W', unitPercent: '%', emptyLoads: '計算するには少なくとも1つの負荷を追加してください。' },
    faq: [{ question: '蓄電池の自給時間とは何ですか？', answer: '入力した負荷の合計電力を、蓄電池が供給できる推定時間です。使用可能容量、開始時の充電率、効率、負荷を使って計算します。' }, { question: '昼間の太陽光発電量も計算しますか？', answer: 'いいえ。夜間または停電時のシナリオ用です。天候、発電量、蓄電池の劣化、パワーコンディショナーの制限、専門的な設計は対象外です。' }, { question: 'なぜ効率を入力するのですか？', answer: 'パワーコンディショナーや配線でエネルギーが失われるためです。公称容量だけを使うより現実的な見積もりになります。' }, { question: '自給時間を延ばすにはどうすればよいですか？', answer: '洗濯、給湯、車の充電などを蓄電池の使用時間帯から移動してください。最もエネルギーを使う負荷が結果に表示されます。' }],
    howTo: [{ name: '使用可能容量を入力する', text: '蓄電池の仕様書にある使用可能エネルギーをキロワット時で入力します。' }, { name: '充電率と効率を設定する', text: '夜間開始時の充電率と、システムの使用可能な効率を設定します。' }, { name: '家庭の負荷を追加する', text: '各機器の電力をワットで、稼働時間を時間で入力します。' }, { name: '結果を行動につなげる', text: '自給時間と最大負荷を見て、移動または停止する機器を決めます。' }],
    sections: ['太陽光蓄電池は夜に何時間使えますか？', '重要なのは蓄電池が何kWhを保存できるかだけではなく、<strong>実際の夜間消費を何時間カバーできるか</strong>です。冷蔵庫、ルーター、照明、充電器はそれぞれ消費の仕方が異なります。負荷を入力してバックアップ時間を確認しましょう。', 'この蓄電池自給時間計算機で分かること', '主な結果は、負荷の合計電力から求めた時間単位の自給時間です。使用可能エネルギー、予定消費、カバー率、不足量も確認できます。最大の負荷が、最初に見直すべき対象を示します。', 'バックアップ計画を改善する', 'まず、消費が大きく時間をずらせる機器を見直します。給湯、洗濯、食器洗い、車の充電は多くの場合、蓄電池の時間帯から移動できます。条件を1つずつ変えて残量を比較してください。', '計算の範囲を理解する', 'これはエネルギー収支のシナリオであり、専門的な蓄電池設計ではありません。天候、発電、劣化、ピーク電力、安全上の制限は設備の仕様書で確認してください。'],
    compare: [{ title: '実際の夜を再現する', description: '夜の全負荷と、重要な負荷だけの計画を比較できます。計算はブラウザー内で行われ、設備には接続しません。', points: ['使用可能容量を使う', '各機器の時間を入力する', 'シナリオを比較する'] }, { title: '見積もりの限界を知る', description: '結果は説明可能なシナリオであり、設計の承認ではありません。蓄電池とインバーターの仕様を確認してください。', points: ['天気予報なし', '劣化モデルなし', '安全判断の代替ではない'] }],
  },
  ko: {
    slug: 'solar-battery-autonomy-calculator', title: '태양광 배터리 자립 시간 계산기', description: '사용 가능한 용량, 시작 충전량, 효율과 가정의 부하를 바탕으로 태양광 배터리의 백업 시간을 추정합니다.',
    ui: { setupEyebrow: '밤 시간 계획', setupTitle: '현실적인 배터리 사용 구간 만들기', capacityLabel: '사용 가능한 배터리 용량', chargeLabel: '시작 충전량', efficiencyLabel: '사용 가능한 효율', loadsTitle: '계속 켜둘 부하', loadName: '부하 이름', loadWatts: '전력', loadHours: '시간', addLoad: '부하 추가', removeLoad: '삭제', resultEyebrow: '핵심 결과', autonomyLabel: '예상 자립 시간', availableEnergy: '현재 사용 가능', plannedDemand: '예정 소비량', afterSchedule: '계획 후 잔량', coverage: '계획 충족률', shortfall: '부족한 에너지', enoughEnergy: '이 계획은 사용 가능한 배터리 에너지 안에 들어옵니다.', biggestLoad: '가장 큰 에너지 소비', shiftSuggestion: '백업 시간을 늘리려면 이 부하부터 시간을 옮기거나 끄세요.', unitKwh: 'kWh', unitHours: '시간', unitWatts: 'W', unitPercent: '%', emptyLoads: '계산하려면 부하를 하나 이상 추가하세요.' },
    faq: [{ question: '배터리 자립 시간이란 무엇인가요?', answer: '입력한 부하의 합산 전력을 배터리가 공급할 수 있는 예상 시간입니다. 사용 가능한 용량, 시작 충전량, 효율과 부하를 사용해 계산합니다.' }, { question: '낮 동안의 태양광 발전량도 계산하나요?', answer: '아니요. 밤이나 비상 전원 시나리오를 위한 계산입니다. 날씨, 발전량, 배터리 열화, 인버터 한계와 전문 설계는 포함하지 않습니다.' }, { question: '효율을 입력하는 이유는 무엇인가요?', answer: '인버터와 배선에서 에너지가 손실되기 때문입니다. 정격 용량만 사용하는 것보다 현실적인 결과를 얻을 수 있습니다.' }, { question: '자립 시간을 늘리려면 어떻게 해야 하나요?', answer: '세탁, 온수, 전기차 충전처럼 조정 가능한 부하를 배터리 사용 시간 밖으로 옮기세요. 가장 많은 에너지를 쓰는 부하가 결과에 표시됩니다.' }],
    howTo: [{ name: '사용 가능한 용량 입력', text: '배터리 설명서에 표시된 사용 가능 에너지를 킬로와트시로 입력합니다.' }, { name: '충전량과 효율 설정', text: '밤이 시작될 때의 충전량과 시스템의 예상 사용 가능 효율을 선택합니다.' }, { name: '가정의 부하 등록', text: '각 기기의 전력과 작동 시간을 입력합니다.' }, { name: '결과에 따라 조정', text: '자립 시간과 최대 부하를 보고 시간을 옮기거나 끌 기기를 결정합니다.' }],
    sections: ['태양광 배터리는 밤에 얼마나 오래 가나요?', '중요한 질문은 배터리가 몇 kWh를 저장하는지만이 아니라 <strong>실제 밤 시간 소비를 몇 시간 동안 감당하는가</strong>입니다. 냉장고, 공유기, 조명, 충전기는 서로 다른 속도로 에너지를 사용합니다. 부하를 입력해 백업 시간을 확인하세요.', '이 배터리 시간 계산기가 알려주는 것', '주요 결과는 모든 부하의 합산 전력을 바탕으로 한 시간 단위의 자립 시간입니다. 사용 가능한 에너지, 예정 소비량, 충족률과 부족량도 확인할 수 있습니다. 가장 큰 소비가 첫 번째 조정 대상을 알려줍니다.', '백업 계획 개선하기', '에너지를 많이 쓰지만 시간을 바꿀 수 있는 부하부터 확인하세요. 온수, 세탁, 식기세척, 차량 충전은 자주 옮길 수 있습니다. 한 번에 하나의 조건만 바꾸고 남은 에너지를 비교하세요.', '계산의 한계 이해하기', '이 결과는 에너지 균형 시나리오이지 전문적인 배터리 용량 산정이 아닙니다. 날씨, 발전, 열화, 피크 전력과 안전 한계는 장비 설명서에서 확인하세요.'],
    compare: [{ title: '실제 밤을 모델링', description: '전체 저녁 사용 패턴과 필수 부하만 남긴 계획을 비교하세요. 계산은 브라우저에서 작동하며 설비에 연결되지 않습니다.', points: ['사용 가능한 용량 사용', '기기별 시간 입력', '시나리오 비교'] }, { title: '한계 확인', description: '결과는 투명한 시나리오일 뿐 설계 승인서가 아닙니다. 배터리와 인버터 문서를 확인하세요.', points: ['날씨 예측 없음', '열화 모델 없음', '안전 조언 아님'] }],
  },
  zh: {
    slug: 'solar-battery-autonomy-calculator', title: '太阳能电池储能续航计算器', description: '根据可用容量、初始电量、效率和家庭负载，估算太阳能电池可以提供多长时间的备用电力。',
    ui: { setupEyebrow: '您的夜间计划', setupTitle: '规划真实的电池使用时段', capacityLabel: '电池可用容量', chargeLabel: '初始电量', efficiencyLabel: '可用效率', loadsTitle: '需要持续运行的负载', loadName: '负载名称', loadWatts: '功率', loadHours: '小时', addLoad: '添加负载', removeLoad: '删除', resultEyebrow: '计算结果', autonomyLabel: '预计续航时间', availableEnergy: '当前可用', plannedDemand: '计划用电量', afterSchedule: '计划后的剩余', coverage: '计划覆盖率', shortfall: '还缺少', enoughEnergy: '该计划在电池可用能量范围内。', biggestLoad: '最大能耗负载', shiftSuggestion: '如果需要更长的备用时间，请优先调整或关闭这个负载。', unitKwh: 'kWh', unitHours: '小时', unitWatts: 'W', unitPercent: '%', emptyLoads: '至少添加一个负载才能查看估算结果。' },
    faq: [{ question: '电池续航是什么意思？', answer: '这是电池为计划中的所有负载提供电力的预计时间。计算会使用可用容量、初始电量、效率以及您输入的负载。' }, { question: '会计算白天的太阳能发电量吗？', answer: '不会。这是夜间或备用电源场景，不包括天气、太阳能发电、电池老化、逆变器限制或专业系统设计。' }, { question: '为什么要考虑效率？', answer: '能量会在逆变器和线路中损失。加入效率后，结果比只使用额定容量更加保守。' }, { question: '如何延长续航时间？', answer: '将洗衣、热水或车辆充电移到电池使用时段之外。结果会显示消耗能量最多的负载。' }],
    howTo: [{ name: '输入可用容量', text: '使用电池资料中标示的可用能量，单位为千瓦时。' }, { name: '设置电量和效率', text: '选择备用时段开始时的电量，以及系统的大致可用效率。' }, { name: '列出家庭负载', text: '输入每个设备的功率和预计运行小时数。' }, { name: '根据结果行动', text: '结合续航时间和最大负载，决定要调整或关闭哪个设备。' }],
    sections: ['太阳能电池夜间可以用多久？', '关键问题不只是电池能储存多少 kWh，而是<strong>它能覆盖您真实夜间用电的多少小时</strong>。冰箱、路由器、照明和充电器的耗电速度不同。输入负载即可得到清晰的备用时间估算。', '这款电池续航计算器能告诉您什么', '主要结果是根据所有负载的总功率计算出的小时数。您还可以看到可用能量、计划用电量、覆盖率和可能的缺口。最大能耗负载会提示最值得先调整的项目。', '改善您的备用电力计划', '先处理耗电量大但时间灵活的负载。热水、洗衣、洗碗和车辆充电通常可以调整时间。每次只改变一个条件，并比较计划结束后的剩余能量。', '了解估算的边界', '这是能量平衡场景，不是专业的电池或系统设计。天气、发电量、老化、峰值功率和安全限制应以设备资料为准。'],
    compare: [{ title: '模拟您的夜晚', description: '比较完整的夜间用电和只保留必要负载的计划。计算在浏览器中完成，不会连接您的设备。', points: ['使用可用容量', '填写每个设备的小时数', '比较不同场景'] }, { title: '理解使用边界', description: '结果是透明的场景估算，不是设计认证。请始终核对电池和逆变器的技术资料。', points: ['不包括天气预测', '不包括老化模型', '不替代安全建议'] }],
  },
};

export const localizedContent = (locale: keyof typeof packs): ToolLocaleContent<SolarBatteryAutonomyCalculatorUI> => makeContent(packs[locale]!, locale);
