export { dewPointCalculator } from './tool/dewPointCalculator/entry';
export type { DewPointCalculatorLocaleContent } from './tool/dewPointCalculator/entry';
export { heatingComparator } from './tool/heatingComparator/entry';
export type { HeatingComparatorLocaleContent } from './tool/heatingComparator/entry';
export { ledSavingCalculator } from './tool/ledSavingCalculator/entry';
export type { LedSavingCalculatorLocaleContent } from './tool/ledSavingCalculator/entry';
export { projectorCalculator } from './tool/projectorCalculator/entry';
export type { ProjectorCalculatorLocaleContent } from './tool/projectorCalculator/entry';
export { qrGenerator } from './tool/qrGenerator/entry';
export type { QRGeneratorLocaleContent } from './tool/qrGenerator/entry';
export { solarCalculator } from './tool/solarCalculator/entry';
export type { SolarCalculatorLocaleContent } from './tool/solarCalculator/entry';
export { tariffComparator } from './tool/tariffComparator/entry';
export type { TariffComparatorLocaleContent } from './tool/tariffComparator/entry';
export { wifiRangeSimulator } from './tool/wifiRangeSimulator/entry';
export type { WifiRangeSimulatorLocaleContent } from './tool/wifiRangeSimulator/entry';
export { acTonnageCalculator } from './tool/acTonnageCalculator/entry';
export type { AcTonnageCalculatorLocaleContent } from './tool/acTonnageCalculator/entry';
export { wallPaintingCalculator } from './tool/wallPaintingCalculator/entry';
export type { WallPaintingCalculatorLocaleContent } from './tool/wallPaintingCalculator/entry';
export { vampireDrawSimulator } from './tool/vampireDrawSimulator/entry';
export type { VampireDrawSimulatorLocaleContent } from './tool/vampireDrawSimulator/entry';
export { deskErgonomics } from './tool/deskErgonomics/entry';
export type { DeskErgonomicsLocaleContent } from './tool/deskErgonomics/entry';
export { applianceCostCalculator } from './tool/applianceCostCalculator/entry';
export type { ApplianceCostCalculatorLocaleContent } from './tool/applianceCostCalculator/entry';
export { tileLayoutCalculator } from './tool/tileLayoutCalculator/entry';
export type { TileLayoutCalculatorLocaleContent } from './tool/tileLayoutCalculator/entry';
export { lightingCalculator } from './tool/lightingCalculator/entry';
export type { LightingCalculatorLocaleContent } from './tool/lightingCalculator/entry';
export { humidityCalculator } from './tool/humidityCalculator/entry';
export type { HumidityCalculatorLocaleContent } from './tool/humidityCalculator/entry';
export { homeCategory } from './category';
import { dewPointCalculator } from './tool/dewPointCalculator/entry';
import { heatingComparator } from './tool/heatingComparator/entry';
import { ledSavingCalculator } from './tool/ledSavingCalculator/entry';
import { projectorCalculator } from './tool/projectorCalculator/entry';
import { qrGenerator } from './tool/qrGenerator/entry';
import { solarCalculator } from './tool/solarCalculator/entry';
import { tariffComparator } from './tool/tariffComparator/entry';
import { wifiRangeSimulator } from './tool/wifiRangeSimulator/entry';
import { acTonnageCalculator } from './tool/acTonnageCalculator/entry';
import { wallPaintingCalculator } from './tool/wallPaintingCalculator/entry';
import { vampireDrawSimulator } from './tool/vampireDrawSimulator/entry';
import { deskErgonomics } from './tool/deskErgonomics/entry';
import { applianceCostCalculator } from './tool/applianceCostCalculator/entry';
import { tileLayoutCalculator } from './tool/tileLayoutCalculator/entry';
import { lightingCalculator } from './tool/lightingCalculator/entry';
import { humidityCalculator } from './tool/humidityCalculator/entry';
export const ALL_ENTRIES = [dewPointCalculator, heatingComparator, ledSavingCalculator, projectorCalculator, qrGenerator, solarCalculator, tariffComparator, wifiRangeSimulator, acTonnageCalculator, wallPaintingCalculator, vampireDrawSimulator, deskErgonomics, applianceCostCalculator, tileLayoutCalculator, lightingCalculator, humidityCalculator];
